export const blindtestGenerationsQuestions = {
  translations: {
    fr: [
      // Noël
      { category: "noel", text: "Vive le vent", answer: "Vive le vent" },
      { category: "noel", text: "Petit Papa Noël", answer: "Petit Papa Noël" },
      { category: "noel", text: "Mon beau sapin", answer: "Mon beau sapin" },
      { category: "noel", text: "Jingle Bells", answer: "Jingle Bells" },
      { category: "noel", text: "All I Want for Christmas Is You", answer: "All I Want for Christmas Is You" },
      { category: "noel", text: "Last Christmas", answer: "Last Christmas" },
      { category: "noel", text: "Douce nuit", answer: "Douce nuit" },
      { category: "noel", text: "L'enfant au tambour", answer: "L'enfant au tambour" },
      { category: "noel", text: "Il est né le divin enfant", answer: "Il est né le divin enfant" },
      { category: "noel", text: "Les anges dans nos campagnes", answer: "Les anges dans nos campagnes" },

      // Génériques TV
      { category: "generiques", text: "Friends", answer: "Friends" },
      { category: "generiques", text: "Game of Thrones", answer: "Game of Thrones" },
      { category: "generiques", text: "The Simpsons", answer: "The Simpsons" },
      { category: "generiques", text: "Breaking Bad", answer: "Breaking Bad" },
      { category: "generiques", text: "Stranger Things", answer: "Stranger Things" },
      { category: "generiques", text: "The Office", answer: "The Office" },
      { category: "generiques", text: "How I Met Your Mother", answer: "How I Met Your Mother" },
      { category: "generiques", text: "Big Bang Theory", answer: "Big Bang Theory" },
      { category: "generiques", text: "Desperate Housewives", answer: "Desperate Housewives" },
      { category: "generiques", text: "Sex and the City", answer: "Sex and the City" },

      // Tubes 80s/90s/2000s
      { category: "tubes-80s-90s-2000s", text: "Billie Jean - Michael Jackson", answer: "Billie Jean" },
      { category: "tubes-80s-90s-2000s", text: "Sweet Child O' Mine - Guns N' Roses", answer: "Sweet Child O' Mine" },
      { category: "tubes-80s-90s-2000s", text: "Smells Like Teen Spirit - Nirvana", answer: "Smells Like Teen Spirit" },
      { category: "tubes-80s-90s-2000s", text: "Wannabe - Spice Girls", answer: "Wannabe" },
      { category: "tubes-80s-90s-2000s", text: "Baby One More Time - Britney Spears", answer: "Baby One More Time" },
      { category: "tubes-80s-90s-2000s", text: "Livin' on a Prayer - Bon Jovi", answer: "Livin' on a Prayer" },
      { category: "tubes-80s-90s-2000s", text: "Don't Stop Believin' - Journey", answer: "Don't Stop Believin'" },
      { category: "tubes-80s-90s-2000s", text: "Eye of the Tiger - Survivor", answer: "Eye of the Tiger" },
      { category: "tubes-80s-90s-2000s", text: "I Want It That Way - Backstreet Boys", answer: "I Want It That Way" },
      { category: "tubes-80s-90s-2000s", text: "Crazy in Love - Beyoncé", answer: "Crazy in Love" },

      // TikTok
      { category: "tiktok", text: "Blinding Lights - The Weeknd", answer: "Blinding Lights" },
      { category: "tiktok", text: "Savage Love - Jawsh 685 & Jason Derulo", answer: "Savage Love" },
      { category: "tiktok", text: "Renegade - K CAMP", answer: "Renegade" },
      { category: "tiktok", text: "Say So - Doja Cat", answer: "Say So" },
      { category: "tiktok", text: "Lottery - K CAMP", answer: "Lottery" },
      { category: "tiktok", text: "Roses - SAINt JHN", answer: "Roses" },
      { category: "tiktok", text: "Supalonely - BENEE", answer: "Supalonely" },
      { category: "tiktok", text: "Cannibal - Kesha", answer: "Cannibal" },
      { category: "tiktok", text: "ROXANNE - Arizona Zervas", answer: "ROXANNE" },
      { category: "tiktok", text: "Toosie Slide - Drake", answer: "Toosie Slide" },

      // Musiques de films
      { category: "films", text: "My Heart Will Go On - Titanic", answer: "My Heart Will Go On" },
      { category: "films", text: "Eye of the Tiger - Rocky", answer: "Eye of the Tiger" },
      { category: "films", text: "I Will Always Love You - The Bodyguard", answer: "I Will Always Love You" },
      { category: "films", text: "Stayin' Alive - Saturday Night Fever", answer: "Stayin' Alive" },
      { category: "films", text: "Shallow - A Star Is Born", answer: "Shallow" },
      { category: "films", text: "The Time of My Life - Dirty Dancing", answer: "The Time of My Life" },
      { category: "films", text: "Let It Go - Frozen", answer: "Let It Go" },
      { category: "films", text: "A Whole New World - Aladdin", answer: "A Whole New World" },
      { category: "films", text: "Circle of Life - The Lion King", answer: "Circle of Life" },
      { category: "films", text: "Skyfall - Skyfall (James Bond)", answer: "Skyfall" },
    ],
    en: [
      // Christmas
      { category: "noel", text: "Jingle Bells", answer: "Jingle Bells" },
      { category: "noel", text: "Silent Night", answer: "Silent Night" },
      { category: "noel", text: "White Christmas", answer: "White Christmas" },
      { category: "noel", text: "All I Want for Christmas Is You", answer: "All I Want for Christmas Is You" },
      { category: "noel", text: "Last Christmas", answer: "Last Christmas" },
      { category: "noel", text: "Feliz Navidad", answer: "Feliz Navidad" },
      { category: "noel", text: "Rudolph the Red-Nosed Reindeer", answer: "Rudolph the Red-Nosed Reindeer" },
      { category: "noel", text: "Deck the Halls", answer: "Deck the Halls" },
      { category: "noel", text: "O Holy Night", answer: "O Holy Night" },
      { category: "noel", text: "The Little Drummer Boy", answer: "The Little Drummer Boy" },

      // TV Show Themes
      { category: "generiques", text: "Friends", answer: "Friends" },
      { category: "generiques", text: "Game of Thrones", answer: "Game of Thrones" },
      { category: "generiques", text: "The Simpsons", answer: "The Simpsons" },
      { category: "generiques", text: "Breaking Bad", answer: "Breaking Bad" },
      { category: "generiques", text: "Stranger Things", answer: "Stranger Things" },
      { category: "generiques", text: "The Office", answer: "The Office" },
      { category: "generiques", text: "How I Met Your Mother", answer: "How I Met Your Mother" },
      { category: "generiques", text: "Big Bang Theory", answer: "Big Bang Theory" },
      { category: "generiques", text: "Desperate Housewives", answer: "Desperate Housewives" },
      { category: "generiques", text: "Sex and the City", answer: "Sex and the City" },

      // 80s/90s/2000s Hits
      { category: "tubes-80s-90s-2000s", text: "Billie Jean - Michael Jackson", answer: "Billie Jean" },
      { category: "tubes-80s-90s-2000s", text: "Sweet Child O' Mine - Guns N' Roses", answer: "Sweet Child O' Mine" },
      { category: "tubes-80s-90s-2000s", text: "Smells Like Teen Spirit - Nirvana", answer: "Smells Like Teen Spirit" },
      { category: "tubes-80s-90s-2000s", text: "Wannabe - Spice Girls", answer: "Wannabe" },
      { category: "tubes-80s-90s-2000s", text: "Baby One More Time - Britney Spears", answer: "Baby One More Time" },
      { category: "tubes-80s-90s-2000s", text: "Livin' on a Prayer - Bon Jovi", answer: "Livin' on a Prayer" },
      { category: "tubes-80s-90s-2000s", text: "Don't Stop Believin' - Journey", answer: "Don't Stop Believin'" },
      { category: "tubes-80s-90s-2000s", text: "Eye of the Tiger - Survivor", answer: "Eye of the Tiger" },
      { category: "tubes-80s-90s-2000s", text: "I Want It That Way - Backstreet Boys", answer: "I Want It That Way" },
      { category: "tubes-80s-90s-2000s", text: "Crazy in Love - Beyoncé", answer: "Crazy in Love" },

      // TikTok
      { category: "tiktok", text: "Blinding Lights - The Weeknd", answer: "Blinding Lights" },
      { category: "tiktok", text: "Savage Love - Jawsh 685 & Jason Derulo", answer: "Savage Love" },
      { category: "tiktok", text: "Renegade - K CAMP", answer: "Renegade" },
      { category: "tiktok", text: "Say So - Doja Cat", answer: "Say So" },
      { category: "tiktok", text: "Lottery - K CAMP", answer: "Lottery" },
      { category: "tiktok", text: "Roses - SAINt JHN", answer: "Roses" },
      { category: "tiktok", text: "Supalonely - BENEE", answer: "Supalonely" },
      { category: "tiktok", text: "Cannibal - Kesha", answer: "Cannibal" },
      { category: "tiktok", text: "ROXANNE - Arizona Zervas", answer: "ROXANNE" },
      { category: "tiktok", text: "Toosie Slide - Drake", answer: "Toosie Slide" },

      // Movie Soundtracks
      { category: "films", text: "My Heart Will Go On - Titanic", answer: "My Heart Will Go On" },
      { category: "films", text: "Eye of the Tiger - Rocky", answer: "Eye of the Tiger" },
      { category: "films", text: "I Will Always Love You - The Bodyguard", answer: "I Will Always Love You" },
      { category: "films", text: "Stayin' Alive - Saturday Night Fever", answer: "Stayin' Alive" },
      { category: "films", text: "Shallow - A Star Is Born", answer: "Shallow" },
      { category: "films", text: "The Time of My Life - Dirty Dancing", answer: "The Time of My Life" },
      { category: "films", text: "Let It Go - Frozen", answer: "Let It Go" },
      { category: "films", text: "A Whole New World - Aladdin", answer: "A Whole New World" },
      { category: "films", text: "Circle of Life - The Lion King", answer: "Circle of Life" },
      { category: "films", text: "Skyfall - Skyfall (James Bond)", answer: "Skyfall" },
    ],
  },
};
