export const dareOrStripQuestions = {
  translations: {
    fr: [
      { text: "Fais un massage sensuel dans le dos de ton/ta partenaire pendant 2 minutes" },
      { text: "Lis un message sexy dans un ton sérieux" },
      { text: "Décris une scène qui te fait fantasmer" },
      { text: "Fais un mini strip-tease de 15 secondes" },
      { text: "Chuchote quelque chose de coquin à l'oreille de ton/ta partenaire" },
      { text: "Embrasse ton/ta partenaire pendant 30 secondes" },
      { text: "Fais un lap dance à ton/ta partenaire" },
      { text: "Raconte ton fantasme le plus fou" },
      { text: "Enlève un vêtement de ton/ta partenaire de manière sensuelle" },
      { text: "Décris ce que tu aimerais faire à ton/ta partenaire ce soir" },
      { text: "Fais un massage des pieds à ton/ta partenaire" },
      { text: "Mords doucement le cou de ton/ta partenaire" },
      { text: "Danse de manière sensuelle pendant 30 secondes" },
      { text: "Caresse le visage de ton/ta partenaire pendant 1 minute" },
      { text: "Raconte ta première expérience intime" },
      { text: "Fais un massage des mains à ton/ta partenaire" },
      { text: "Murmure ton désir le plus secret" },
      { text: "Embrasse ton/ta partenaire là où il/elle le souhaite" },
      { text: "Fais un slow collé-serré avec ton/ta partenaire" },
      { text: "Décris la partie du corps de ton/ta partenaire que tu préfères" },
      { text: "Fais un compliment sensuel à ton/ta partenaire" },
      { text: "Raconte ce qui t'excite le plus" },
      { text: "Masse les épaules de ton/ta partenaire pendant 2 minutes" },
      { text: "Fais un bisou dans le cou de ton/ta partenaire" },
      { text: "Décris ton moment intime préféré avec ton/ta partenaire" },
      { text: "Fais semblant de séduire ton/ta partenaire comme si c'était votre première rencontre" },
      { text: "Raconte un rêve érotique que tu as fait" },
      { text: "Embrasse délicatement l'épaule de ton/ta partenaire" },
      { text: "Fais un massage du cuir chevelu à ton/ta partenaire" },
      { text: "Dis à ton/ta partenaire ce que tu aimerais essayer de nouveau" },
    ],
    en: [
      { text: "Give your partner a sensual back massage for 2 minutes" },
      { text: "Read a sexy message in a serious tone" },
      { text: "Describe a scene that turns you on" },
      { text: "Do a mini strip-tease for 15 seconds" },
      { text: "Whisper something naughty in your partner's ear" },
      { text: "Kiss your partner for 30 seconds" },
      { text: "Give your partner a lap dance" },
      { text: "Tell your wildest fantasy" },
      { text: "Remove one piece of clothing from your partner sensually" },
      { text: "Describe what you'd like to do to your partner tonight" },
      { text: "Give your partner a foot massage" },
      { text: "Gently bite your partner's neck" },
      { text: "Dance sensually for 30 seconds" },
      { text: "Caress your partner's face for 1 minute" },
      { text: "Tell about your first intimate experience" },
      { text: "Give your partner a hand massage" },
      { text: "Whisper your deepest desire" },
      { text: "Kiss your partner wherever they want" },
      { text: "Slow dance close with your partner" },
      { text: "Describe your favorite body part of your partner" },
      { text: "Give your partner a sensual compliment" },
      { text: "Tell what turns you on the most" },
      { text: "Massage your partner's shoulders for 2 minutes" },
      { text: "Kiss your partner's neck" },
      { text: "Describe your favorite intimate moment with your partner" },
      { text: "Pretend to seduce your partner as if it was your first meeting" },
      { text: "Tell an erotic dream you had" },
      { text: "Gently kiss your partner's shoulder" },
      { text: "Give your partner a scalp massage" },
      { text: "Tell your partner something new you'd like to try" },
    ],
  },
};
