export const listenButDontJudgeQuestions = 
    translations: {
      fr: [
        "Si {playerName} devait confesser un péché mignon, lequel serait-ce ?",
        "Quelle est la pire habitude de {playerName} qu'il/elle n'admettra jamais publiquement ?",
        "Comment {playerName} réagirait face à un compliment sincère mais inattendu ?",
        "Quel secret {playerName} serait-il/elle prêt(e) à partager avec nous aujourd'hui ?",
        "Qu'est-ce qui rend {playerName} vraiment unique selon vous ?",
        "Quelle qualité admirez-vous le plus chez {playerName} ?",
        "Si {playerName} était un personnage de film ou de série, lequel serait-il/elle et pourquoi ?",
        "Quelle est la plus grande peur de {playerName} d'après vous ?",
        "Comment imaginez-vous la vie de {playerName} dans 10 ans ?",
        "Quelle est la chose la plus gentille que {playerName} ait jamais faite pour quelqu'un ?",
        "Si {playerName} pouvait changer une chose dans sa vie, quelle serait-elle selon vous ?",
        "Quelle situation fait le plus douter {playerName} de ses capacités ?",
        "Quel est le rêve secret de {playerName} selon vous ?",
        "Quelle est la plus belle qualité cachée de {playerName} ?",
        "Si {playerName} écrivait un livre, quel en serait le titre ?",
        "Comment {playerName} exprime-t-il/elle son affection ?",
        "Quel compliment {playerName} aimerait-il/elle entendre plus souvent ?",
        "Quelle est la plus grande force de {playerName} en amitié ?",
        "Si {playerName} avait une baguette magique, que changerait-il/elle en premier ?",
        "Quel est le talent caché de {playerName} que peu de gens connaissent ?",
        "Comment {playerName} gère-t-il/elle le stress selon vous ?",
        "Quelle est la chose qui fait le plus sourire {playerName} ?",
        "Si {playerName} était un super-héros, quel serait son pouvoir ?",
        "Quelle est la plus grande leçon que {playerName} a apprise dans sa vie ?",
        "Comment {playerName} montre-t-il/elle qu'il/elle tient à quelqu'un ?",
        "Si {playerName} pouvait revivre un moment de sa vie, lequel choisirait-il/elle ?",
        "Quelle est la chose que {playerName} fait mieux que tout le monde ?",
        "Si {playerName} était un animal, lequel serait-il et pourquoi ?",
        "Comment {playerName} inspire-t-il/elle les autres sans s'en rendre compte ?",
        "Si {playerName} pouvait donner un conseil au monde entier, que dirait-il/elle ?",
        "Comment {playerName} voit-il/elle l'amour idéal ?",
        "Si {playerName} était une chanson, laquelle serait-ce ?",
        "Comment {playerName} réconforte-t-il/elle ses proches ?",
        "Si {playerName} pouvait rencontrer une personne célèbre, qui choisirait-il/elle ?",
        "Comment {playerName} définit-il/elle le bonheur selon vous ?",
        "Comment {playerName} exprime-t-il/elle sa créativité ?",
        "Si {playerName} pouvait apprendre instantanément une compétence, laquelle choisirait-il/elle ?",
        "Comment {playerName} imagine-t-il/elle sa retraite idéale ?",
        "Si {playerName} était un parfum, quelle serait son essence ?",
        "Comment {playerName} réagit-il/elle quand personne ne le/la regarde ?",
        "Si {playerName} pouvait changer le monde, par quoi commencerait-il/elle ?",
        "Comment {playerName} célèbre-t-il/elle ses petites victoires ?",
        "Si {playerName} était un dessert, lequel serait-il et pourquoi ?",
        "Comment {playerName} gère-t-il/elle les moments difficiles ?",
        "Si {playerName} pouvait posséder un objet magique, lequel choisirait-il/elle ?",
        "Comment {playerName} exprime-t-il/elle sa reconnaissance ?",
        "Si {playerName} était une couleur, laquelle serait-ce et pourquoi ?",
        "Comment {playerName} montre-t-il/elle qu'il/elle est heureux/se ?",
        "Si {playerName} pouvait voyager dans le temps, quelle époque visiterait-il/elle ?",
        "Quelle est la plus belle leçon que la vie a enseignée à {playerName} ?",
      ],
      en: [
        "If {playerName} had to confess a cute sin, what would it be?",
        "What is {playerName}'s worst habit that they would never publicly admit?",
        "How would {playerName} react to a sincere but unexpected compliment?",
        "What secret would {playerName} be willing to share with us today?",
        "What makes {playerName} truly unique in your opinion?",
        "What quality do you admire most about {playerName}?",
        "If {playerName} were a movie or TV series character, which one would they be and why?",
        "What do you think is {playerName}'s biggest fear?",
        "How do you imagine {playerName}'s life in 10 years?",
        "What is the kindest thing {playerName} has ever done for someone?",
        "If {playerName} could change one thing in their life, what do you think it would be?",
        "What situation makes {playerName} doubt their abilities the most?",
        "What do you think is {playerName}'s secret dream?",
        "What is {playerName}'s most beautiful hidden quality?",
        "If {playerName} wrote a book, what would the title be?",
        "How does {playerName} express affection?",
        "What compliment would {playerName} like to hear more often?",
        "What is {playerName}'s greatest strength in friendship?",
        "If {playerName} had a magic wand, what would they change first?",
        "What is {playerName}'s hidden talent that few people know about?",
        "How do you think {playerName} handles stress?",
        "What is the thing that makes {playerName} smile the most?",
        "If {playerName} were a superhero, what would their power be?",
        "What is the greatest lesson {playerName} has learned in life?",
        "How does {playerName} show that they care about someone?",
        "If {playerName} could relive one moment of their life, which would they choose?",
        "What is the thing {playerName} does better than anyone else?",
        "If {playerName} were an animal, which one would they be and why?",
        "How does {playerName} inspire others without realizing it?",
        "If {playerName} could give advice to the whole world, what would they say?",
        "How does {playerName} view ideal love?",
        "If {playerName} were a song, which one would it be?",
        "How does {playerName} comfort their loved ones?",
        "If {playerName} could meet a famous person, who would they choose?",
        "How do you think {playerName} defines happiness?",
        "How does {playerName} express their creativity?",
        "If {playerName} could instantly learn a skill, which would they choose?",
        "How does {playerName} imagine their ideal retirement?",
        "If {playerName} were a perfume, what would be their essence?",
        "How does {playerName} act when no one is watching?",
        "If {playerName} could change the world, where would they start?",
        "How does {playerName} celebrate their small victories?",
        "If {playerName} were a dessert, which would they be and why?",
        "How does {playerName} handle difficult moments?",
        "If {playerName} could own a magical object, which would they choose?",
        "How does {playerName} express gratitude?",
        "If {playerName} were a color, which would it be and why?",
        "How does {playerName} show that they are happy?",
        "If {playerName} could time travel, what era would they visit?",
        "What is the most beautiful lesson life has taught {playerName}?",
      ],
      es: [
        "Si {playerName} tuviera que confesar un pecado adorable, ¿cuál sería?",
        "¿Cuál es el peor hábito de {playerName} que nunca admitiría públicamente?",
        "¿Cómo reaccionaría {playerName} ante un cumplido sincero pero inesperado?",
        "¿Qué secreto estaría {playerName} dispuesto/a a compartir con nosotros hoy?",
        "¿Qué hace que {playerName} sea verdaderamente único/a en tu opinión?",
        "¿Qué cualidad admiras más de {playerName}?",
        "Si {playerName} fuera un personaje de película o serie, ¿cuál sería y por qué?",
        "¿Cuál crees que es el mayor miedo de {playerName}?",
        "¿Cómo imaginas la vida de {playerName} en 10 años?",
        "¿Cuál es la cosa más amable que {playerName} ha hecho por alguien?",
        "Si {playerName} pudiera cambiar una cosa en su vida, ¿qué crees que sería?",
        "¿Qué situación hace que {playerName} dude más de sus capacidades?",
        "¿Cuál crees que es el sueño secreto de {playerName}?",
        "¿Cuál es la cualidad oculta más hermosa de {playerName}?",
        "Si {playerName} escribiera un libro, ¿cuál sería el título?",
        "¿Cómo expresa {playerName} el cariño?",
        "¿Qué cumplido le gustaría a {playerName} escuchar más a menudo?",
        "¿Cuál es la mayor fortaleza de {playerName} en la amistad?",
        "Si {playerName} tuviera una varita mágica, ¿qué cambiaría primero?",
        "¿Cuál es el talento oculto de {playerName} que poca gente conoce?",
        "¿Cómo crees que {playerName} maneja el estrés?",
        "¿Qué es lo que más hace sonreír a {playerName}?",
        "Si {playerName} fuera un superhéroe, ¿cuál sería su poder?",
        "¿Cuál es la lección más grande que {playerName} ha aprendido en la vida?",
        "¿Cómo demuestra {playerName} que le importa alguien?",
        "Si {playerName} pudiera revivir un momento de su vida, ¿cuál elegiría?",
        "¿Qué es lo que {playerName} hace mejor que nadie?",
        "Si {playerName} fuera un animal, ¿cuál sería y por qué?",
        "¿Cómo inspira {playerName} a otros sin darse cuenta?",
        "Si {playerName} pudiera dar un consejo al mundo entero, ¿qué diría?",
        "¿Cómo ve {playerName} el amor ideal?",
        "Si {playerName} fuera una canción, ¿cuál sería?",
        "¿Cómo consuela {playerName} a sus seres queridos?",
        "Si {playerName} pudiera conocer a una persona famosa, ¿a quién elegiría?",
        "¿Cómo crees que {playerName} define la felicidad?",
        "¿Cómo expresa {playerName} su creatividad?",
        "Si {playerName} pudiera aprender instantáneamente una habilidad, ¿cuál elegiría?",
        "¿Cómo imagina {playerName} su jubilación ideal?",
        "Si {playerName} fuera un perfume, ¿cuál sería su esencia?",
        "¿Cómo actúa {playerName} cuando nadie lo/la mira?",
        "Si {playerName} pudiera cambiar el mundo, ¿por dónde empezaría?",
        "¿Cómo celebra {playerName} sus pequeñas victorias?",
        "Si {playerName} fuera un postre, ¿cuál sería y por qué?",
        "¿Cómo maneja {playerName} los momentos difíciles?",
        "Si {playerName} pudiera poseer un objeto mágico, ¿cuál elegiría?",
        "¿Cómo expresa {playerName} la gratitud?",
        "Si {playerName} fuera un color, ¿cuál sería y por qué?",
        "¿Cómo demuestra {playerName} que está feliz?",
        "Si {playerName} pudiera viajar en el tiempo, ¿qué época visitaría?",
        "¿Cuál es la lección más hermosa que la vida ha enseñado a {playerName}?",
      ],
      de: [
        "Wenn {playerName} eine niedliche Sünde gestehen müsste, welche wäre das?",
        "Was ist die schlimmste Angewohnheit von {playerName}, die er/sie nie öffentlich zugeben würde?",
        "Wie würde {playerName} auf ein aufrichtiges, aber unerwartetes Kompliment reagieren?",
        "Welches Geheimnis wäre {playerName} bereit, heute mit uns zu teilen?",
        "Was macht {playerName} deiner Meinung nach wirklich einzigartig?",
        "Welche Eigenschaft bewunderst du am meisten an {playerName}?",
        "Wenn {playerName} eine Film- oder Fernsehfigur wäre, welche wäre es und warum?",
        "Was ist deiner Meinung nach die größte Angst von {playerName}?",
        "Wie stellst du dir das Leben von {playerName} in 10 Jahren vor?",
        "Was ist das Netteste, was {playerName} jemals für jemanden getan hat?",
        "Wenn {playerName} eine Sache in seinem/ihrem Leben ändern könnte, was wäre es deiner Meinung nach?",
        "Welche Situation lässt {playerName} am meisten an seinen/ihren Fähigkeiten zweifeln?",
        "Was ist deiner Meinung nach der geheime Traum von {playerName}?",
        "Was ist die schönste versteckte Eigenschaft von {playerName}?",
        "Wenn {playerName} ein Buch schreiben würde, wie würde der Titel lauten?",
        "Wie drückt {playerName} Zuneigung aus?",
        "Welches Kompliment würde {playerName} gerne öfter hören?",
        "Was ist {playerName}s größte Stärke in der Freundschaft?",
        "Wenn {playerName} einen Zauberstab hätte, was würde er/sie zuerst ändern?",
        "Was ist das versteckte Talent von {playerName}, das nur wenige kennen?",
        "Wie denkst du, geht {playerName} mit Stress um?",
        "Was bringt {playerName} am meisten zum Lächeln?",
        "Wenn {playerName} ein Superheld wäre, was wäre seine/ihre Kraft?",
        "Was ist die größte Lektion, die {playerName} im Leben gelernt hat?",
        "Wie zeigt {playerName}, dass ihm/ihr jemand wichtig ist?",
        "Wenn {playerName} einen Moment seines/ihres Lebens wiederleben könnte, welchen würde er/sie wählen?",
        "Was macht {playerName} besser als alle anderen?",
        "Wenn {playerName} ein Tier wäre, welches wäre es und warum?",
        "Wie inspiriert {playerName} andere, ohne es zu merken?",
        "Wenn {playerName} der ganzen Welt einen Rat geben könnte, was würde er/sie sagen?",
        "Wie sieht {playerName} die ideale Liebe?",
        "Wenn {playerName} ein Lied wäre, welches wäre es?",
        "Wie tröstet {playerName} seine/ihre Lieben?",
        "Wenn {playerName} eine berühmte Person treffen könnte, wen würde er/sie wählen?",
        "Wie definiert {playerName} deiner Meinung nach Glück?",
        "Wie drückt {playerName} seine/ihre Kreativität aus?",
        "Wenn {playerName} sofort eine Fähigkeit erlernen könnte, welche würde er/sie wählen?",
        "Wie stellt sich {playerName} seinen/ihren idealen Ruhestand vor?",
        "Wenn {playerName} ein Parfüm wäre, was wäre seine/ihre Essenz?",
        "Wie verhält sich {playerName}, wenn niemand hinschaut?",
        "Wenn {playerName} die Welt verändern könnte, womit würde er/sie anfangen?",
        "Wie feiert {playerName} seine/ihre kleinen Siege?",
        "Wenn {playerName} ein Dessert wäre, welches wäre es und warum?",
        "Wie geht {playerName} mit schwierigen Momenten um?",
        "Wenn {playerName} einen magischen Gegenstand besitzen könnte, welchen würde er/sie wählen?",
        "Wie drückt {playerName} Dankbarkeit aus?",
        "Wenn {playerName} eine Farbe wäre, welche wäre es und warum?",
        "Wie zeigt {playerName}, dass er/sie glücklich ist?",
        "Wenn {playerName} durch die Zeit reisen könnte, welche Epoche würde er/sie besuchen?",
        "Was ist die schönste Lektion, die das Leben {playerName} gelehrt hat?",
      ],
      it: [
        "Se {playerName} dovesse confessare un piccolo peccato, quale sarebbe?",
        "Qual è la peggiore abitudine di {playerName} che non ammetterebbe mai pubblicamente?",
        "Come reagirebbe {playerName} a un complimento sincero ma inaspettato?",
        "Quale segreto {playerName} sarebbe disposto/a a condividere con noi oggi?",
        "Cosa rende {playerName} veramente unico/a secondo te?",
        "Quale qualità ammiri di più in {playerName}?",
        "Se {playerName} fosse un personaggio di un film o di una serie TV, quale sarebbe e perché?",
        "Qual è secondo te la più grande paura di {playerName}?",
        "Come immagini la vita di {playerName} tra 10 anni?",
        "Qual è la cosa più gentile che {playerName} ha mai fatto per qualcuno?",
        "Se {playerName} potesse cambiare una cosa nella sua vita, quale pensi che sarebbe?",
        "Quale situazione fa dubitare maggiormente {playerName} delle proprie capacità?",
        "Qual è secondo te il sogno segreto di {playerName}?",
        "Qual è la più bella qualità nascosta di {playerName}?",
        "Se {playerName} scrivesse un libro, quale sarebbe il titolo?",
        "Come esprime {playerName} l'affetto?",
        "Quale complimento a {playerName} piacerebbe sentire più spesso?",
        "Qual è il più grande punto di forza di {playerName} nell'amicizia?",
        "Se {playerName} avesse una bacchetta magica, cosa cambierebbe per primo?",
        "Qual è il talento nascosto di {playerName} che poche persone conoscono?",
        "Come pensi che {playerName} gestisca lo stress?",
        "Qual è la cosa che fa sorridere di più {playerName}?",
        "Se {playerName} fosse un supereroe, quale sarebbe il suo potere?",
        "Qual è la lezione più grande che {playerName} ha imparato nella vita?",
        "Come dimostra {playerName} che tiene a qualcuno?",
        "Se {playerName} potesse rivivere un momento della sua vita, quale sceglierebbe?",
        "Qual è la cosa che {playerName} fa meglio di chiunque altro?",
        "Se {playerName} fosse un animale, quale sarebbe e perché?",
        "Come ispira {playerName} gli altri senza rendersene conto?",
        "Se {playerName} potesse dare un consiglio al mondo intero, cosa direbbe?",
        "Come vede {playerName} l'amore ideale?",
        "Se {playerName} fosse una canzone, quale sarebbe?",
        "Come consola {playerName} i suoi cari?",
        "Se {playerName} potesse incontrare una persona famosa, chi sceglierebbe?",
        "Come pensi che {playerName} definisca la felicità?",
        "Come esprime {playerName} la sua creatività?",
        "Se {playerName} potesse imparare istantaneamente una habilidad, quale sceglierebbe?",
        "Come immagina {playerName} la sua pensione ideale?",
        "Se {playerName} fosse un profumo, quale sarebbe la sua essenza?",
        "Come si comporta {playerName} quando nessuno lo/la guarda?",
        "Se {playerName} potesse cambiare il mondo, da dove inizierebbe?",
        "Come celebra {playerName} le sue piccole vittorie?",
        "Se {playerName} fosse una sobremesa, quale sarebbe e perché?",
        "Come affronta {playerName} i momenti difficili?",
        "Se {playerName} potesse possedere un oggetto magico, quale sceglierebbe?",
        "Come esprime {playerName} la gratitudine?",
        "Se {playerName} fosse un colore, quale sarebbe e perché?",
        "Come dimostra {playerName} che è felice?",
        "Se {playerName} potesse viaggiare nel tempo, quale epoca visiterebbe?",
        "Qual è la lezione più bella che la vita ha insegnato a {playerName}?",
      ],
      pt: [
        "Se {playerName} tivesse que confessar um pecado fofo, qual seria?",
        "Qual é o pior hábito de {playerName} que ele/ela nunca admitiria publicamente?",
        "Como {playerName} reagiria a um elogio sincero, mas inesperado?",
        "Que segredo {playerName} estaria disposto/a a compartilhar conosco hoje?",
        "O que torna {playerName} verdadeiramente único/a na sua opinião?",
        "Que qualidade você mais admira em {playerName}?",
        "Se {playerName} fosse um personagem de filme ou série, qual seria e por quê?",
        "Qual você acha que é o maior medo de {playerName}?",
        "Como você imagina a vida de {playerName} daqui a 10 anos?",
        "Qual é a coisa mais gentil que {playerName} já fez por alguém?",
        "Se {playerName} pudesse mudar uma coisa em sua vida, o que você acha que seria?",
        "Que situação faz {playerName} duvidar mais de suas habilidades?",
        "Qual você acha que é o sonho secreto de {playerName}?",
        "Qual é a mais bela qualidade oculta de {playerName}?",
        "Se {playerName} escrevesse um livro, qual seria o título?",
        "Como {playerName} expressa carinho?",
        "Que elogio {playerName} gostaria de ouvir mais frequentemente?",
        "Qual é a maior força de {playerName} na amizade?",
        "Se {playerName} tivesse uma varinha mágica, o que mudaria primeiro?",
        "Qual é o talento oculto de {playerName} que poucas pessoas conhecem?",
        "Como você acha que {playerName} lida com o estresse?",
        "O que mais faz {playerName} sorrir?",
        "Se {playerName} fosse um super-herói, qual seria seu poder?",
        "Qual é a maior lição que {playerName} aprendeu na vida?",
        "Como {playerName} demonstra que se importa com alguém?",
        "Se {playerName} pudesse reviver um momento de sua vida, qual escolheria?",
        "O que {playerName} faz melhor que qualquer outra pessoa?",
        "Se {playerName} fosse um animal, qual seria e por quê?",
        "Como {playerName} inspira outros sem perceber?",
        "Se {playerName} pudesse dar um conselho ao mundo inteiro, o que diria?",
        "Como {playerName} vê o amor ideal?",
        "Se {playerName} fosse uma música, qual seria?",
        "Como {playerName} consola seus entes queridos?",
        "Se {playerName} pudesse conhecer uma pessoa famosa, quem escolheria?",
        "Como você acha que {playerName} define felicidade?",
        "Como {playerName} expressa sua criatividade?",
        "Se {playerName} pudesse aprender instantaneamente uma habilidade, qual escolheria?",
        "Como {playerName} imagina sua aposentadoria ideal?",
        "Se {playerName} fosse um perfume, qual seria sua essência?",
        "Como {playerName} age quando ninguém está olhando?",
        "Se {playerName} pudesse mudar o mundo, por onde começaria?",
        "Como {playerName} celebra suas pequenas vitórias?",
        "Se {playerName} fosse uma sobremesa, qual seria e por quê?",
        "Como {playerName} lida com momentos difíceis?",
        "Se {playerName} pudesse possuir um objeto mágico, qual escolheria?",
        "Como {playerName} expressa gratidão?",
        "Se {playerName} fosse uma cor, qual seria e por quê?",
        "Como {playerName} demonstra que está feliz?",
        "Se {playerName} pudesse viajar no tempo, que época visitaria?",
        "Qual é a mais bela lição que a vida ensinou a {playerName}?",
      ],
      ar: [
        "إذا كان على {playerName} الاعتراف بخطيئة لطيفة، فماذا ستكون؟",
        "ما هي أسوأ عادة لدى {playerName} لن يعترف بها أبدًا علنًا؟",
        "كيف سيتفاعل {playerName} مع مجاملة صادقة ولكنها غير متوقعة؟",
        "ما هو السر الذي سيكون {playerName} على استعداد لمشاركته معنا اليوم؟",
        "ما الذي يجعل {playerName} فريدًا حقًا في رأيك؟",
        "ما هي الصفة التي تعجبك أكثر في {playerName}؟",
        "إذا كان {playerName} شخصية في فيلم أو مسلسل تلفزيوني، فأي شخصية سيكون ولماذا؟",
        "ما هو برأيك أكبر خوف لدى {playerName}؟",
        "كيف تتخيل حياة {playerName} بعد 10 سنوات؟",
        "ما هو ألطف شيء قام به {playerName} لشخص ما؟",
        "إذا كان بإمكان {playerName} تغيير شيء واحد في حياته، ما الذي تعتقد أنه سيكون؟",
        "ما هو الموقف الذي يجعل {playerName} يشك في قدراته أكثر؟",
        "ما الذي تعتقد أنه الحلم السري لـ {playerName}؟",
        "ما هي أجمل صفة مخفية لدى {playerName}؟",
        "إذا كتب {playerName} كتابًا، فما سيكون عنوانه؟",
        "كيف يعبر {playerName} عن المودة؟",
        "أي مجاملة يحب {playerName} أن يسمعها أكثر؟",
        "ما هي أكبر نقطة قوة لدى {playerName} في الصداقة؟",
        "إذا كان لدى {playerName} عصا سحرية، فما الذي سيغيره أولاً؟",
        "ما هي الموهبة المخفية لدى {playerName} التي يعرفها القليل من الناس؟",
        "كيف تعتقد أن {playerName} يتعامل مع التوتر؟",
        "ما الذي يجعل {playerName} يبتسم أكثر؟",
        "إذا كان {playerName} بطلاً خارقًا، فما ستكون قوته؟",
        "ما هي أعظم درس تعلمه {playerName} في الحياة؟",
        "كيف يُظهر {playerName} اهتمامه بشخص ما؟",
        "إذا كان بإمكان {playerName} إعادة عيش لحظة من حياته، فأيها سيختار؟",
        "ما الذي يفعله {playerName} أفضل من أي شخص آخر؟",
        "إذا كان {playerName} حيوانًا، فأي حيوان سيكون ولماذا؟",
        "كيف يلهم {playerName} الآخرين دون أن يدرك ذلك؟",
        "إذا كان بإمكان {playerName} إعطاء نصيحة للعالم كله، فماذا سيقول؟",
        "كيف يرى {playerName} الحب المثالي؟",
        "إذا كان {playerName} أغنية، فأي أغنية ستكون؟",
        "كيف يواسي {playerName} أحباءه؟",
        "إذا كان بإمكان {playerName} مقابلة شخصية مشهورة، فمن سيختار؟",
        "كيف تعتقد أن {playerName} يعرّف السعادة؟",
        "كيف يعبر {playerName} عن إبداعه؟",
        "إذا كان بإمكان {playerName} تعلم مهارة فورًا، فأيها سيختار؟",
        "كيف يتخيل {playerName} تقاعده المثالي؟",
        "إذا كان {playerName} عطرًا، فما ستكون جوهره؟",
        "كيف يتصرف {playerName} عندما لا يراقبه أحد؟",
        "إذا كان بإمكان {playerName} تغيير العالم، فمن أين سيبدأ؟",
        "كيف يحتفل {playerName} بانتصاراته الصغيرة؟",
        "إذا كان {playerName} حلوى، فأي حلوى سيكون ولماذا؟",
        "كيف يتعامل {playerName} مع اللحظات الصعبة؟",
        "إذا كان بإمكان {playerName} امتلاك شيء سحري، فماذا سيختار؟",
        "كيف يعبر {playerName} عن الامتنان؟",
        "إذا كان {playerName} لونًا، فأي لون سيكون ولماذا؟",
        "كيف يُظهر {playerName} أنه سعيد؟",
        "إذا كان بإمكان {playerName} السفر عبر الزمن، فأي عصر سيزور؟",
        "ما هي أجمل درس علمته الحياة لـ {playerName}؟",
      ],
    },
  },
};
