export const trapAnswerQuestions = 
    translations: {
      fr: [
        {
          type: "culture",
          question: "Où a été inventé le croissant ?",
          answer: "Autriche",
          traps: ["France", "Italie", "Belgique"],
        },
        {
          type: "nature",
          question: "Quel est l'animal le plus rapide sur terre ?",
          answer: "Guépard",
          traps: ["Aigle royal", "Lièvre", "Zèbre"],
        },
        {
          type: "art",
          question: "Qui a peint la Joconde ?",
          answer: "Léonard de Vinci",
          traps: ["Michel-Ange", "Raphaël", "Botticelli"],
        },
        {
          type: "géographie",
          question: "Quelle est la capitale de l'Australie ?",
          answer: "Canberra",
          traps: ["Sydney", "Melbourne", "Brisbane"],
        },
        {
          type: "géographie",
          question: "Quel est le plus grand océan du monde ?",
          answer: "Océan Pacifique",
          traps: ["Océan Atlantique", "Océan Indien", "Océan Arctique"],
        },
        {
          type: "histoire",
          question: "Qui a inventé l'ampoule électrique ?",
          answer: "Thomas Edison",
          traps: ["Nikola Tesla", "Benjamin Franklin", "Alexander Bell"],
        },
        {
          type: "science",
          question: "Combien de cœurs a une pieuvre ?",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "culture",
          question: "Dans quel pays a été inventé le sushi ?",
          answer: "Chine",
          traps: ["Japon", "Corée", "Thaïlande"],
        },
        {
          type: "nature",
          question: "Quel animal ne peut pas marcher à reculons ?",
          answer: "Kangourou",
          traps: ["Éléphant", "Girafe", "Pingouin"],
        },
        {
          type: "science",
          question: "Quelle planète est la plus chaude du système solaire ?",
          answer: "Vénus",
          traps: ["Mercure", "Mars", "Jupiter"],
        },
        {
          type: "géographie",
          question: "Quel pays a le plus de fuseaux horaires ?",
          answer: "France",
          traps: ["Russie", "États-Unis", "Chine"],
        },
        {
          type: "histoire",
          question: "Quel peuple a inventé le papier ?",
          answer: "Chinois",
          traps: ["Égyptiens", "Grecs", "Romains"],
        },
        {
          type: "nature",
          question: "Quel est le plus grand mammifère terrestre ?",
          answer: "Éléphant d'Afrique",
          traps: ["Baleine bleue", "Rhinocéros", "Hippopotame"],
        },
        {
          type: "culture",
          question: "Quelle boisson contient le plus de caféine ?",
          answer: "Thé matcha",
          traps: ["Café espresso", "Red Bull", "Coca-Cola"],
        },
        {
          type: "science",
          question: "Quel organe humain consomme le plus d'énergie ?",
          answer: "Cerveau",
          traps: ["Cœur", "Foie", "Muscles"],
        },
        {
          type: "géographie",
          question: "Quel désert est le plus grand au monde ?",
          answer: "Antarctique",
          traps: ["Sahara", "Gobi", "Kalahari"],
        },
        {
          type: "histoire",
          question: "Quelle civilisation a inventé l'écriture ?",
          answer: "Sumériens",
          traps: ["Égyptiens", "Chinois", "Grecs"],
        },
        {
          type: "nature",
          question: "Quel fruit contient le plus de vitamine C ?",
          answer: "Acérola",
          traps: ["Orange", "Citron", "Kiwi"],
        },
        {
          type: "science",
          question: "Quel métal est liquide à température ambiante ?",
          answer: "Mercure",
          traps: ["Plomb", "Étain", "Zinc"],
        },
        {
          type: "culture",
          question: "Quel pays a inventé la pizza ?",
          answer: "Grèce antique",
          traps: ["Italie", "États-Unis", "France"],
        },
        {
          type: "nature",
          question: "Quel animal a la morsure la plus puissante ?",
          answer: "Crocodile du Nil",
          traps: ["Grand requin blanc", "Lion", "Hyène"],
        },
        {
          type: "géographie",
          question: "Quel pays a la plus longue côte au monde ?",
          answer: "Canada",
          traps: ["Norvège", "Australie", "Russie"],
        },
        {
          type: "science",
          question: "Combien d'os a un requin ?",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "histoire",
          question: "Qui a découvert l'Amérique en premier ?",
          answer: "Leif Erikson",
          traps: ["Christophe Colomb", "Amerigo Vespucci", "Magellan"],
        },
        {
          type: "culture",
          question: "Dans quel pays boit-on le plus de thé par habitant ?",
          answer: "Turquie",
          traps: ["Chine", "Inde", "Angleterre"],
        },
        {
          type: "nature",
          question: "Quel insecte peut soulever 50 fois son poids ?",
          answer: "Fourmi",
          traps: ["Scarabée", "Abeille", "Sauterelle"],
        },
        {
          type: "science",
          question: "Quelle couleur absorbe le plus la chaleur ?",
          answer: "Noir",
          traps: ["Rouge", "Bleu foncé", "Violet"],
        },
        {
          type: "géographie",
          question: "Quelle ville est surnommée la 'Venise du Nord' ?",
          answer: "Amsterdam",
          traps: ["Stockholm", "Bruges", "Saint-Pétersbourg"],
        },
        {
          type: "histoire",
          question: "Quel empire a duré le plus longtemps ?",
          answer: "Empire byzantin",
          traps: ["Empire romain", "Empire ottoman", "Empire britannique"],
        },
        {
          type: "culture",
          question: "Quel fromage est le plus consommé au monde ?",
          answer: "Mozzarella",
          traps: ["Cheddar", "Gouda", "Camembert"],
        },
        {
          type: "nature",
          question: "Quel animal dort le plus par jour ?",
          answer: "Koala",
          traps: ["Paresseux", "Chat", "Chauve-souris"],
        },
        {
          type: "science",
          question: "Quel gaz compose principalement l'atmosphère ?",
          answer: "Azote",
          traps: ["Oxygène", "Dioxyde de carbone", "Argon"],
        },
        {
          type: "géographie",
          question: "Quel pays a le plus de lacs au monde ?",
          answer: "Finlande",
          traps: ["Canada", "Suède", "Russie"],
        },
        {
          type: "histoire",
          question: "Quelle guerre a duré le plus longtemps ?",
          answer: "Guerre de Cent Ans",
          traps: ["Guerre de Trente Ans", "Guerre froide", "Reconquista"],
        },
        {
          type: "culture",
          question: "Quel instrument a le plus de cordes ?",
          answer: "Piano",
          traps: ["Harpe", "Guitare", "Violon"],
        },
        {
          type: "nature",
          question: "Quel oiseau peut voler à reculons ?",
          answer: "Colibri",
          traps: ["Aigle", "Faucon", "Moineau"],
        },
        {
          type: "science",
          question: "Quel est l'élément le plus abondant dans l'univers ?",
          answer: "Hydrogène",
          traps: ["Oxygène", "Carbone", "Hélium"],
        },
        {
          type: "géographie",
          question: "Quelle montagne grandit chaque année ?",
          answer: "Mont Everest",
          traps: ["Mont Blanc", "Kilimandjaro", "Mont Fuji"],
        },
        {
          type: "histoire",
          question: "Qui a inventé l'imprimerie ?",
          answer: "Bi Sheng",
          traps: ["Gutenberg", "Caxton", "Plantin"],
        },
        {
          type: "culture",
          question: "Quel pays produit le plus de café ?",
          answer: "Brésil",
          traps: ["Colombie", "Vietnam", "Éthiopie"],
        },
        {
          type: "nature",
          question: "Quel animal a le plus d'estomacs ?",
          answer: "Vache",
          traps: ["Mouton", "Cheval", "Porc"],
        },
        {
          type: "science",
          question: "À quelle température l'eau est-elle la plus dense ?",
          answer: "4°C",
          traps: ["0°C", "20°C", "100°C"],
        },
        {
          type: "géographie",
          question: "Quel pays a la plus haute espérance de vie ?",
          answer: "Monaco",
          traps: ["Japon", "Suisse", "Singapour"],
        },
        {
          type: "histoire",
          question: "Quelle révolution a eu lieu en premier ?",
          answer: "Révolution anglaise",
          traps: [
            "Révolution française",
            "Révolution américaine",
            "Révolution russe",
          ],
        },
        {
          type: "culture",
          question: "Quel sport a été inventé en premier ?",
          answer: "Lutte",
          traps: ["Course à pied", "Natation", "Boxe"],
        },
        {
          type: "nature",
          question: "Quel animal vit le plus longtemps ?",
          answer: "Méduse immortelle",
          traps: ["Tortue", "Baleine", "Requin"],
        },
        {
          type: "science",
          question: "Combien de dimensions a l'espace-temps selon Einstein ?",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "géographie",
          question: "Quel fleuve traverse le plus de pays ?",
          answer: "Danube",
          traps: ["Nil", "Amazone", "Rhin"],
        },
        {
          type: "histoire",
          question: "Quelle langue était parlée par Jésus ?",
          answer: "Araméen",
          traps: ["Hébreu", "Latin", "Grec"],
        },
        {
          type: "culture",
          question: "Quel pays a inventé les pâtes ?",
          answer: "Chine",
          traps: ["Italie", "Grèce", "Perse"],
        },
      ],
      en: [
        {
          type: "culture",
          question: "Where was the croissant invented?",
          answer: "Austria",
          traps: ["France", "Italy", "Belgium"],
        },
        {
          type: "nature",
          question: "What is the fastest animal on land?",
          answer: "Cheetah",
          traps: ["Golden Eagle", "Hare", "Zebra"],
        },
        {
          type: "art",
          question: "Who painted the Mona Lisa?",
          answer: "Leonardo da Vinci",
          traps: ["Michelangelo", "Raphael", "Botticelli"],
        },
        {
          type: "geography",
          question: "What is the capital of Australia?",
          answer: "Canberra",
          traps: ["Sydney", "Melbourne", "Brisbane"],
        },
        {
          type: "geography",
          question: "What is the largest ocean in the world?",
          answer: "Pacific Ocean",
          traps: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
        },
        {
          type: "history",
          question: "Who invented the light bulb?",
          answer: "Thomas Edison",
          traps: ["Nikola Tesla", "Benjamin Franklin", "Alexander Bell"],
        },
        {
          type: "science",
          question: "How many hearts does an octopus have?",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "culture",
          question: "In which country was sushi invented?",
          answer: "China",
          traps: ["Japan", "Korea", "Thailand"],
        },
        {
          type: "nature",
          question: "Which animal cannot walk backwards?",
          answer: "Kangaroo",
          traps: ["Elephant", "Giraffe", "Penguin"],
        },
        {
          type: "science",
          question: "Which planet is the hottest in our solar system?",
          answer: "Venus",
          traps: ["Mercury", "Mars", "Jupiter"],
        },
        {
          type: "geography",
          question: "Which country has the most time zones?",
          answer: "France",
          traps: ["Russia", "United States", "China"],
        },
        {
          type: "history",
          question: "Which people invented paper?",
          answer: "Chinese",
          traps: ["Egyptians", "Greeks", "Romans"],
        },
        {
          type: "nature",
          question: "What is the largest land mammal?",
          answer: "African Elephant",
          traps: ["Blue Whale", "Rhinoceros", "Hippopotamus"],
        },
        {
          type: "culture",
          question: "Which drink contains the most caffeine?",
          answer: "Matcha tea",
          traps: ["Espresso coffee", "Red Bull", "Coca-Cola"],
        },
        {
          type: "science",
          question: "Which human organ consumes the most energy?",
          answer: "Brain",
          traps: ["Heart", "Liver", "Muscles"],
        },
        {
          type: "geography",
          question: "Which is the largest desert in the world?",
          answer: "Antarctica",
          traps: ["Sahara", "Gobi", "Kalahari"],
        },
        {
          type: "history",
          question: "Which civilization invented writing?",
          answer: "Sumerians",
          traps: ["Egyptians", "Chinese", "Greeks"],
        },
        {
          type: "nature",
          question: "Which fruit contains the most vitamin C?",
          answer: "Acerola",
          traps: ["Orange", "Lemon", "Kiwi"],
        },
        {
          type: "science",
          question: "Which metal is liquid at room temperature?",
          answer: "Mercury",
          traps: ["Lead", "Tin", "Zinc"],
        },
        {
          type: "culture",
          question: "Which country invented pizza?",
          answer: "Ancient Greece",
          traps: ["Italy", "United States", "France"],
        },
        {
          type: "nature",
          question: "Which animal has the strongest bite?",
          answer: "Nile Crocodile",
          traps: ["Great White Shark", "Lion", "Hyena"],
        },
        {
          type: "geography",
          question: "Which country has the longest coastline in the world?",
          answer: "Canada",
          traps: ["Norway", "Australia", "Russia"],
        },
        {
          type: "science",
          question: "How many bones does a shark have?",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "history",
          question: "Who discovered America first?",
          answer: "Leif Erikson",
          traps: ["Christopher Columbus", "Amerigo Vespucci", "Magellan"],
        },
        {
          type: "culture",
          question: "Which country drinks the most tea per capita?",
          answer: "Turkey",
          traps: ["China", "India", "England"],
        },
        {
          type: "nature",
          question: "Which insect can lift 50 times its weight?",
          answer: "Ant",
          traps: ["Beetle", "Bee", "Grasshopper"],
        },
        {
          type: "science",
          question: "Which color absorbs the most heat?",
          answer: "Black",
          traps: ["Red", "Dark blue", "Purple"],
        },
        {
          type: "geography",
          question: "Which city is nicknamed the 'Venice of the North'?",
          answer: "Amsterdam",
          traps: ["Stockholm", "Bruges", "St. Petersburg"],
        },
        {
          type: "history",
          question: "Which empire lasted the longest?",
          answer: "Byzantine Empire",
          traps: ["Roman Empire", "Ottoman Empire", "British Empire"],
        },
        {
          type: "culture",
          question: "Which cheese is most consumed worldwide?",
          answer: "Mozzarella",
          traps: ["Cheddar", "Gouda", "Camembert"],
        },
        {
          type: "nature",
          question: "Which animal sleeps the most per day?",
          answer: "Koala",
          traps: ["Sloth", "Cat", "Bat"],
        },
        {
          type: "science",
          question: "Which gas mainly composes the atmosphere?",
          answer: "Nitrogen",
          traps: ["Oxygen", "Carbon dioxide", "Argon"],
        },
        {
          type: "geography",
          question: "Which country has the most lakes in the world?",
          answer: "Finland",
          traps: ["Canada", "Sweden", "Russia"],
        },
        {
          type: "history",
          question: "Which war lasted the longest?",
          answer: "Hundred Years' War",
          traps: ["Thirty Years' War", "Cold War", "Reconquista"],
        },
        {
          type: "culture",
          question: "Which instrument has the most strings?",
          answer: "Piano",
          traps: ["Harp", "Guitar", "Violin"],
        },
        {
          type: "nature",
          question: "Which bird can fly backwards?",
          answer: "Hummingbird",
          traps: ["Eagle", "Falcon", "Sparrow"],
        },
        {
          type: "science",
          question: "What is the most abundant element in the universe?",
          answer: "Hydrogen",
          traps: ["Oxygen", "Carbon", "Helium"],
        },
        {
          type: "geography",
          question: "Which mountain grows every year?",
          answer: "Mount Everest",
          traps: ["Mont Blanc", "Kilimanjaro", "Mount Fuji"],
        },
        {
          type: "history",
          question: "Who invented the printing press?",
          answer: "Bi Sheng",
          traps: ["Gutenberg", "Caxton", "Plantin"],
        },
        {
          type: "culture",
          question: "Which country produces the most coffee?",
          answer: "Brazil",
          traps: ["Colombia", "Vietnam", "Ethiopia"],
        },
        {
          type: "nature",
          question: "Which animal has the most stomachs?",
          answer: "Cow",
          traps: ["Sheep", "Horse", "Pig"],
        },
        {
          type: "science",
          question: "At what temperature is water most dense?",
          answer: "4°C",
          traps: ["0°C", "20°C", "100°C"],
        },
        {
          type: "geography",
          question: "Which country has the highest life expectancy?",
          answer: "Monaco",
          traps: ["Japan", "Switzerland", "Singapore"],
        },
        {
          type: "history",
          question: "Which revolution happened first?",
          answer: "English Revolution",
          traps: [
            "French Revolution",
            "American Revolution",
            "Russian Revolution",
          ],
        },
        {
          type: "culture",
          question: "Which sport was invented first?",
          answer: "Wrestling",
          traps: ["Running", "Swimming", "Boxing"],
        },
        {
          type: "nature",
          question: "Which animal lives the longest?",
          answer: "Immortal Jellyfish",
          traps: ["Turtle", "Whale", "Shark"],
        },
        {
          type: "science",
          question:
            "How many dimensions does space-time have according to Einstein?",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "geography",
          question: "Which river crosses the most countries?",
          answer: "Danube",
          traps: ["Nile", "Amazon", "Rhine"],
        },
        {
          type: "history",
          question: "What language did Jesus speak?",
          answer: "Aramaic",
          traps: ["Hebrew", "Latin", "Greek"],
        },
        {
          type: "culture",
          question: "Which country invented pasta?",
          answer: "China",
          traps: ["Italy", "Greece", "Persia"],
        },
      ],
      es: [
        {
          type: "cultura",
          question: "¿Dónde se inventó el croissant?",
          answer: "Austria",
          traps: ["Francia", "Italia", "Bélgica"],
        },
        {
          type: "naturaleza",
          question: "¿Cuál es el animal más rápido en tierra?",
          answer: "Guepardo",
          traps: ["Águila Real", "Liebre", "Cebra"],
        },
        {
          type: "arte",
          question: "¿Quién pintó la Mona Lisa?",
          answer: "Leonardo da Vinci",
          traps: ["Miguel Ángel", "Rafael", "Botticelli"],
        },
        {
          type: "geografía",
          question: "¿Cuál es la capital de Australia?",
          answer: "Canberra",
          traps: ["Sídney", "Melbourne", "Brisbane"],
        },
        {
          type: "geografía",
          question: "¿Cuál es el océano más grande del mundo?",
          answer: "Océano Pacífico",
          traps: ["Océano Atlántico", "Océano Índico", "Océano Ártico"],
        },
        {
          type: "historia",
          question: "¿Quién inventó la bombilla eléctrica?",
          answer: "Thomas Edison",
          traps: ["Nikola Tesla", "Benjamin Franklin", "Alexander Bell"],
        },
        {
          type: "ciencia",
          question: "¿Cuántos corazones tiene un pulpo?",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "cultura",
          question: "¿En qué país se inventó el sushi?",
          answer: "China",
          traps: ["Japón", "Corea", "Tailandia"],
        },
        {
          type: "naturaleza",
          question: "¿Qué animal no puede caminar hacia atrás?",
          answer: "Canguro",
          traps: ["Elefante", "Jirafa", "Pingüino"],
        },
        {
          type: "ciencia",
          question: "¿Qué planeta es el más caliente del sistema solar?",
          answer: "Venus",
          traps: ["Mercurio", "Marte", "Júpiter"],
        },
        {
          type: "geografía",
          question: "¿Qué país tiene más husos horarios?",
          answer: "Francia",
          traps: ["Rusia", "Estados Unidos", "China"],
        },
        {
          type: "historia",
          question: "¿Qué pueblo inventó el papel?",
          answer: "Chinos",
          traps: ["Egipcios", "Griegos", "Romanos"],
        },
        {
          type: "naturaleza",
          question: "¿Cuál es el mamífero terrestre más grande?",
          answer: "Elefante africano",
          traps: ["Ballena azul", "Rinoceronte", "Hipopótamo"],
        },
        {
          type: "cultura",
          question: "¿Qué bebida contiene más cafeína?",
          answer: "Té matcha",
          traps: ["Café espresso", "Red Bull", "Coca-Cola"],
        },
        {
          type: "ciencia",
          question: "¿Qué órgano humano consume más energía?",
          answer: "Cerebro",
          traps: ["Corazón", "Hígado", "Músculos"],
        },
        {
          type: "geografía",
          question: "¿Cuál es el desierto más grande del mundo?",
          answer: "Antártida",
          traps: ["Sahara", "Gobi", "Kalahari"],
        },
        {
          type: "historia",
          question: "¿Qué civilización inventó la escritura?",
          answer: "Sumerios",
          traps: ["Egipcios", "Chinos", "Griegos"],
        },
        {
          type: "naturaleza",
          question: "¿Qué fruta contiene más vitamina C?",
          answer: "Acerola",
          traps: ["Naranja", "Limón", "Kiwi"],
        },
        {
          type: "ciencia",
          question: "¿Qué metal es líquido a temperatura ambiente?",
          answer: "Mercurio",
          traps: ["Plomo", "Estaño", "Zinc"],
        },
        {
          type: "cultura",
          question: "¿Qué país inventó la pizza?",
          answer: "Grecia antigua",
          traps: ["Italia", "Estados Unidos", "Francia"],
        },
        {
          type: "naturaleza",
          question: "¿Qué animal tiene la mordida más fuerte?",
          answer: "Cocodrilo del Nilo",
          traps: ["Gran tiburón blanco", "León", "Hiena"],
        },
        {
          type: "geografía",
          question: "¿Qué país tiene la costa más larga del mundo?",
          answer: "Canadá",
          traps: ["Noruega", "Australia", "Rusia"],
        },
        {
          type: "ciencia",
          question: "¿Cuántos huesos tiene un tiburón?",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "historia",
          question: "¿Quién descubrió América primero?",
          answer: "Leif Erikson",
          traps: ["Cristóbal Colón", "Amerigo Vespucci", "Magallanes"],
        },
        {
          type: "cultura",
          question: "¿Qué país bebe más té per cápita?",
          answer: "Turquía",
          traps: ["China", "India", "Inglaterra"],
        },
        {
          type: "naturaleza",
          question: "¿Qué insecto puede levantar 50 veces su peso?",
          answer: "Hormiga",
          traps: ["Escarabajo", "Abeja", "Saltamontes"],
        },
        {
          type: "ciencia",
          question: "¿Qué color absorbe más calor?",
          answer: "Negro",
          traps: ["Rojo", "Azul oscuro", "Morado"],
        },
        {
          type: "geografía",
          question: "¿Qué ciudad es apodada la 'Venecia del Norte'?",
          answer: "Ámsterdam",
          traps: ["Estocolmo", "Brujas", "San Petersburgo"],
        },
        {
          type: "historia",
          question: "¿Qué imperio duró más tiempo?",
          answer: "Imperio bizantino",
          traps: ["Imperio romano", "Imperio otomano", "Imperio británico"],
        },
        {
          type: "cultura",
          question: "¿Qué queso se consume más en el mundo?",
          answer: "Mozzarella",
          traps: ["Cheddar", "Gouda", "Camembert"],
        },
        {
          type: "naturaleza",
          question: "¿Qué animal duerme más por día?",
          answer: "Koala",
          traps: ["Perezoso", "Gato", "Murciélago"],
        },
        {
          type: "ciencia",
          question: "¿Qué gas compone principalmente la atmósfera?",
          answer: "Nitrógeno",
          traps: ["Oxígeno", "Dióxido de carbono", "Argón"],
        },
        {
          type: "geografía",
          question: "¿Qué país tiene más lagos en el mundo?",
          answer: "Finlandia",
          traps: ["Canadá", "Suecia", "Rusia"],
        },
        {
          type: "historia",
          question: "¿Qué guerra duró más tiempo?",
          answer: "Guerra de los Cien Años",
          traps: ["Guerra de los Treinta Años", "Guerra Fría", "Reconquista"],
        },
        {
          type: "cultura",
          question: "¿Qué instrumento tiene más cuerdas?",
          answer: "Piano",
          traps: ["Arpa", "Guitarra", "Violín"],
        },
        {
          type: "naturaleza",
          question: "¿Qué ave puede volar hacia atrás?",
          answer: "Colibrí",
          traps: ["Águila", "Halcón", "Gorrión"],
        },
        {
          type: "ciencia",
          question: "¿Cuál es el elemento más abundante en el universo?",
          answer: "Hidrógeno",
          traps: ["Oxígeno", "Carbono", "Helio"],
        },
        {
          type: "geografía",
          question: "¿Qué montaña crece cada año?",
          answer: "Monte Everest",
          traps: ["Mont Blanc", "Kilimanjaro", "Monte Fuji"],
        },
        {
          type: "historia",
          question: "¿Quién inventó la imprenta?",
          answer: "Bi Sheng",
          traps: ["Gutenberg", "Caxton", "Plantin"],
        },
        {
          type: "cultura",
          question: "¿Qué país produce más café?",
          answer: "Brasil",
          traps: ["Colombia", "Vietnam", "Etiopía"],
        },
        {
          type: "naturaleza",
          question: "¿Qué animal tiene más estómagos?",
          answer: "Vaca",
          traps: ["Oveja", "Caballo", "Cerdo"],
        },
        {
          type: "ciencia",
          question: "¿A qué temperatura es más densa el agua?",
          answer: "4°C",
          traps: ["0°C", "20°C", "100°C"],
        },
        {
          type: "geografía",
          question: "¿Qué país tiene la mayor esperanza de vida?",
          answer: "Mónaco",
          traps: ["Japón", "Suiza", "Singapur"],
        },
        {
          type: "historia",
          question: "¿Qué revolución ocurrió primero?",
          answer: "Revolución inglesa",
          traps: [
            "Revolución francesa",
            "Revolución americana",
            "Revolución rusa",
          ],
        },
        {
          type: "cultura",
          question: "¿Qué deporte se inventó primero?",
          answer: "Lucha",
          traps: ["Carrera", "Natación", "Boxeo"],
        },
        {
          type: "naturaleza",
          question: "¿Qué animal vive más tiempo?",
          answer: "Medusa inmortal",
          traps: ["Tortuga", "Ballena", "Tiburón"],
        },
        {
          type: "ciencia",
          question:
            "¿Cuántas dimensiones tiene el espacio-tiempo según Einstein?",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "geografía",
          question: "¿Qué río cruza más países?",
          answer: "Danubio",
          traps: ["Nilo", "Amazonas", "Rin"],
        },
        {
          type: "historia",
          question: "¿Qué idioma hablaba Jesús?",
          answer: "Arameo",
          traps: ["Hebreo", "Latín", "Griego"],
        },
        {
          type: "cultura",
          question: "¿Qué país inventó la pasta?",
          answer: "China",
          traps: ["Italia", "Grecia", "Persia"],
        },
      ],
      de: [
        {
          type: "kultur",
          question: "Wo wurde das Croissant erfunden?",
          answer: "Österreich",
          traps: ["Frankreich", "Italien", "Belgien"],
        },
        {
          type: "natur",
          question: "Welches ist das schnellste Tier an Land?",
          answer: "Gepard",
          traps: ["Steinadler", "Hase", "Zebra"],
        },
        {
          type: "kunst",
          question: "Wer hat die Mona Lisa gemalt?",
          answer: "Leonardo da Vinci",
          traps: ["Michelangelo", "Raffael", "Botticelli"],
        },
        {
          type: "geographie",
          question: "Was ist die Hauptstadt von Australien?",
          answer: "Canberra",
          traps: ["Sydney", "Melbourne", "Brisbane"],
        },
        {
          type: "geographie",
          question: "Welcher ist der größte Ozean der Welt?",
          answer: "Pazifischer Ozean",
          traps: ["Atlantischer Ozean", "Indischer Ozean", "Arktischer Ozean"],
        },
        {
          type: "geschichte",
          question: "Wer hat die Glühbirne erfunden?",
          answer: "Thomas Edison",
          traps: ["Nikola Tesla", "Benjamin Franklin", "Alexander Bell"],
        },
        {
          type: "wissenschaft",
          question: "Wie viele Herzen hat ein Oktopus?",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "kultur",
          question: "In welchem Land wurde Sushi erfunden?",
          answer: "China",
          traps: ["Japan", "Korea", "Thailand"],
        },
        {
          type: "natur",
          question: "Welches Tier kann nicht rückwärts gehen?",
          answer: "Känguru",
          traps: ["Elefant", "Giraffe", "Pinguin"],
        },
        {
          type: "wissenschaft",
          question: "Welcher Planet ist der heißeste in unserem Sonnensystem?",
          answer: "Venus",
          traps: ["Merkur", "Mars", "Jupiter"],
        },
        {
          type: "geographie",
          question: "Welches Land hat die meisten Zeitzonen?",
          answer: "Frankreich",
          traps: ["Russland", "USA", "China"],
        },
        {
          type: "geschichte",
          question: "Welches Volk hat das Papier erfunden?",
          answer: "Chinesen",
          traps: ["Ägypter", "Griechen", "Römer"],
        },
        {
          type: "natur",
          question: "Was ist das größte Landtier?",
          answer: "Afrikanischer Elefant",
          traps: ["Blauwal", "Nashorn", "Nilpferd"],
        },
        {
          type: "kultur",
          question: "Welches Getränk enthält am meisten Koffein?",
          answer: "Matcha-Tee",
          traps: ["Espresso", "Red Bull", "Coca-Cola"],
        },
        {
          type: "wissenschaft",
          question: "Welches menschliche Organ verbraucht am meisten Energie?",
          answer: "Gehirn",
          traps: ["Herz", "Leber", "Muskeln"],
        },
        {
          type: "geographie",
          question: "Welche ist die größte Wüste der Welt?",
          answer: "Antarktis",
          traps: ["Sahara", "Gobi", "Kalahari"],
        },
        {
          type: "geschichte",
          question: "Welche Zivilisation hat die Schrift erfunden?",
          answer: "Sumerer",
          traps: ["Ägypter", "Chinesen", "Griechen"],
        },
        {
          type: "natur",
          question: "Welche Frucht enthält am meisten Vitamin C?",
          answer: "Acerola",
          traps: ["Orange", "Zitrone", "Kiwi"],
        },
        {
          type: "wissenschaft",
          question: "Welches Metall ist bei Raumtemperatur flüssig?",
          answer: "Quecksilber",
          traps: ["Blei", "Zinn", "Zink"],
        },
        {
          type: "kultur",
          question: "Welches Land hat die Pizza erfunden?",
          answer: "Antikes Griechenland",
          traps: ["Italien", "USA", "Frankreich"],
        },
        {
          type: "natur",
          question: "Welches Tier hat den stärksten Biss?",
          answer: "Nilkrokodil",
          traps: ["Weißer Hai", "Löwe", "Hyäne"],
        },
        {
          type: "geographie",
          question: "Welches Land hat die längste Küste der Welt?",
          answer: "Kanada",
          traps: ["Norwegen", "Australien", "Russland"],
        },
        {
          type: "wissenschaft",
          question: "Wie viele Knochen hat ein Hai?",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "geschichte",
          question: "Wer entdeckte Amerika zuerst?",
          answer: "Leif Erikson",
          traps: ["Christoph Kolumbus", "Amerigo Vespucci", "Magellan"],
        },
        {
          type: "kultur",
          question: "Welches Land trinkt pro Kopf am meisten Tee?",
          answer: "Türkei",
          traps: ["China", "Indien", "England"],
        },
        {
          type: "natur",
          question: "Welches Insekt kann das 50-fache seines Gewichts heben?",
          answer: "Ameise",
          traps: ["Käfer", "Biene", "Heuschrecke"],
        },
        {
          type: "wissenschaft",
          question: "Welche Farbe absorbiert am meisten Wärme?",
          answer: "Schwarz",
          traps: ["Rot", "Dunkelblau", "Lila"],
        },
        {
          type: "geographie",
          question: "Welche Stadt wird 'Venedig des Nordens' genannt?",
          answer: "Amsterdam",
          traps: ["Stockholm", "Brügge", "St. Petersburg"],
        },
        {
          type: "geschichte",
          question: "Welches Reich bestand am längsten?",
          answer: "Byzantinisches Reich",
          traps: ["Römisches Reich", "Osmanisches Reich", "Britisches Reich"],
        },
        {
          type: "kultur",
          question: "Welcher Käse wird weltweit am meisten konsumiert?",
          answer: "Mozzarella",
          traps: ["Cheddar", "Gouda", "Camembert"],
        },
        {
          type: "natur",
          question: "Welches Tier schläft pro Tag am meisten?",
          answer: "Koala",
          traps: ["Faultier", "Katze", "Fledermaus"],
        },
        {
          type: "wissenschaft",
          question: "Welches Gas macht hauptsächlich die Atmosphäre aus?",
          answer: "Stickstoff",
          traps: ["Sauerstoff", "Kohlendioxid", "Argon"],
        },
        {
          type: "geographie",
          question: "Welches Land hat die meisten Seen der Welt?",
          answer: "Finnland",
          traps: ["Kanada", "Schweden", "Russland"],
        },
        {
          type: "geschichte",
          question: "Welcher Krieg dauerte am längsten?",
          answer: "Hundertjähriger Krieg",
          traps: ["Dreißigjähriger Krieg", "Kalter Krieg", "Reconquista"],
        },
        {
          type: "kultur",
          question: "Welches Instrument hat die meisten Saiten?",
          answer: "Klavier",
          traps: ["Harfe", "Gitarre", "Geige"],
        },
        {
          type: "natur",
          question: "Welcher Vogel kann rückwärts fliegen?",
          answer: "Kolibri",
          traps: ["Adler", "Falke", "Spatz"],
        },
        {
          type: "wissenschaft",
          question: "Was ist das häufigste Element im Universum?",
          answer: "Wasserstoff",
          traps: ["Sauerstoff", "Kohlenstoff", "Helium"],
        },
        {
          type: "geographie",
          question: "Welcher Berg wächst jedes Jahr?",
          answer: "Mount Everest",
          traps: ["Mont Blanc", "Kilimandscharo", "Mount Fuji"],
        },
        {
          type: "geschichte",
          question: "Wer erfand den Buchdruck?",
          answer: "Bi Sheng",
          traps: ["Gutenberg", "Caxton", "Plantin"],
        },
        {
          type: "kultur",
          question: "Welches Land produziert den meisten Kaffee?",
          answer: "Brasilien",
          traps: ["Kolumbien", "Vietnam", "Äthiopien"],
        },
        {
          type: "natur",
          question: "Welches Tier hat die meisten Mägen?",
          answer: "Kuh",
          traps: ["Schaf", "Pferd", "Schwein"],
        },
        {
          type: "wissenschaft",
          question: "Bei welcher Temperatur ist Wasser am dichtesten?",
          answer: "4°C",
          traps: ["0°C", "20°C", "100°C"],
        },
        {
          type: "geographie",
          question: "Welches Land hat die höchste Lebenserwartung?",
          answer: "Monaco",
          traps: ["Japan", "Schweiz", "Singapur"],
        },
        {
          type: "geschichte",
          question: "Welche Revolution geschah zuerst?",
          answer: "Englische Revolution",
          traps: [
            "Französische Revolution",
            "Amerikanische Revolution",
            "Russische Revolution",
          ],
        },
        {
          type: "kultur",
          question: "Welcher Sport wurde zuerst erfunden?",
          answer: "Ringen",
          traps: ["Laufen", "Schwimmen", "Boxen"],
        },
        {
          type: "natur",
          question: "Welches Tier lebt am längsten?",
          answer: "Unsterbliche Qualle",
          traps: ["Schildkröte", "Wal", "Hai"],
        },
        {
          type: "wissenschaft",
          question: "Wie viele Dimensionen hat die Raumzeit nach Einstein?",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "geographie",
          question: "Welcher Fluss durchquert die meisten Länder?",
          answer: "Donau",
          traps: ["Nil", "Amazonas", "Rhein"],
        },
        {
          type: "geschichte",
          question: "Welche Sprache sprach Jesus?",
          answer: "Aramäisch",
          traps: ["Hebräisch", "Latein", "Griechisch"],
        },
        {
          type: "kultur",
          question: "Welches Land erfand die Nudeln?",
          answer: "China",
          traps: ["Italien", "Griechenland", "Persien"],
        },
      ],
      it: [
        {
          type: "cultura",
          question: "Dove è stato inventato il croissant?",
          answer: "Austria",
          traps: ["Francia", "Italia", "Belgio"],
        },
        {
          type: "natura",
          question: "Qual è l'animale più veloce sulla terra?",
          answer: "Ghepardo",
          traps: ["Aquila reale", "Lepre", "Zebra"],
        },
        {
          type: "arte",
          question: "Chi ha dipinto la Gioconda?",
          answer: "Leonardo da Vinci",
          traps: ["Michelangelo", "Raffaello", "Botticelli"],
        },
        {
          type: "geografia",
          question: "Qual è la capitale dell'Australia?",
          answer: "Canberra",
          traps: ["Sydney", "Melbourne", "Brisbane"],
        },
        {
          type: "geografia",
          question: "Qual è l'oceano più grande del mondo?",
          answer: "Oceano Pacifico",
          traps: ["Oceano Atlantico", "Oceano Indiano", "Oceano Artico"],
        },
        {
          type: "storia",
          question: "Chi ha inventato la lampadina elettrica?",
          answer: "Thomas Edison",
          traps: ["Nikola Tesla", "Benjamin Franklin", "Alexander Bell"],
        },
        {
          type: "scienza",
          question: "Quanti cuori ha un polpo?",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "cultura",
          question: "In quale paese è stato inventato il sushi?",
          answer: "Cina",
          traps: ["Giappone", "Corea", "Tailandia"],
        },
        {
          type: "natura",
          question: "Quale animale non può camminare all'indietro?",
          answer: "Canguro",
          traps: ["Elefante", "Giraffa", "Pinguino"],
        },
        {
          type: "scienza",
          question: "Quale pianeta è il più caldo del sistema solare?",
          answer: "Venere",
          traps: ["Mercurio", "Marte", "Giove"],
        },
        {
          type: "geografia",
          question: "Quale paese ha più fusi orari?",
          answer: "Francia",
          traps: ["Russia", "Stati Uniti", "Cina"],
        },
        {
          type: "storia",
          question: "Quale popolo ha inventato la carta?",
          answer: "Cinesi",
          traps: ["Egizi", "Greci", "Romani"],
        },
        {
          type: "natura",
          question: "Qual è il mammifero terrestre più grande?",
          answer: "Elefante africano",
          traps: ["Balenottera azzurra", "Rinoceronte", "Ippopotamo"],
        },
        {
          type: "cultura",
          question: "Quale bevanda contiene più caffeina?",
          answer: "Tè matcha",
          traps: ["Caffè espresso", "Red Bull", "Coca-Cola"],
        },
        {
          type: "scienza",
          question: "Quale organo umano consume più energia?",
          answer: "Cervello",
          traps: ["Cuore", "Fegato", "Muscoli"],
        },
        {
          type: "geografia",
          question: "Qual è il deserto più grande del mondo?",
          answer: "Antartide",
          traps: ["Sahara", "Gobi", "Kalahari"],
        },
        {
          type: "storia",
          question: "Quale civiltà ha inventato la scrittura?",
          answer: "Sumeri",
          traps: ["Egizi", "Cinesi", "Greci"],
        },
        {
          type: "natura",
          question: "Quale frutto contiene più vitamina C?",
          answer: "Acerola",
          traps: ["Arancia", "Limone", "Kiwi"],
        },
        {
          type: "scienza",
          question: "Quale metallo è liquido a temperatura ambiente?",
          answer: "Mercurio",
          traps: ["Piombo", "Stagno", "Zinco"],
        },
        {
          type: "cultura",
          question: "Quale paese ha inventato la pizza?",
          answer: "Grecia antica",
          traps: ["Italia", "Stati Uniti", "Francia"],
        },
        {
          type: "natura",
          question: "Quale animale ha il morso più forte?",
          answer: "Coccodrillo del Nilo",
          traps: ["Grande squalo bianco", "Leone", "Iena"],
        },
        {
          type: "geografia",
          question: "Quale paese ha la costa più lunga del mondo?",
          answer: "Canada",
          traps: ["Norvegia", "Australia", "Russia"],
        },
        {
          type: "scienza",
          question: "Quante ossa ha uno squalo?",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "storia",
          question: "Chi ha scoperto l'America per primo?",
          answer: "Leif Erikson",
          traps: ["Cristoforo Colombo", "Amerigo Vespucci", "Magellano"],
        },
        {
          type: "cultura",
          question: "Quale paese beve più tè pro capite?",
          answer: "Turchia",
          traps: ["Cina", "India", "Inghilterra"],
        },
        {
          type: "natura",
          question: "Quale insetto può sollevare 50 volte il suo peso?",
          answer: "Formiga",
          traps: ["Scarabeo", "Ape", "Cavalletta"],
        },
        {
          type: "scienza",
          question: "Quale colore assorbe più calore?",
          answer: "Nero",
          traps: ["Rosso", "Blu scuro", "Viola"],
        },
        {
          type: "geografia",
          question: "Quale città è soprannominata la 'Venezia del Nord'?",
          answer: "Amsterdam",
          traps: ["Stoccolma", "Bruges", "San Pietroburgo"],
        },
        {
          type: "storia",
          question: "Quale impero è durato più a lungo?",
          answer: "Impero bizantino",
          traps: ["Impero romano", "Impero ottomano", "Impero britannico"],
        },
        {
          type: "cultura",
          question: "Quale formaggio è più consumato al mondo?",
          answer: "Mozzarella",
          traps: ["Cheddar", "Gouda", "Camembert"],
        },
        {
          type: "natura",
          question: "Quale animale dorme di più al giorno?",
          answer: "Koala",
          traps: ["Bradipo", "Gatto", "Pipistrello"],
        },
        {
          type: "scienza",
          question: "Quale gas compone principalmente l'atmosfera?",
          answer: "Azoto",
          traps: ["Ossigeno", "Anidride carbonica", "Argon"],
        },
        {
          type: "geografia",
          question: "Quale paese ha più laghi al mondo?",
          answer: "Finlandia",
          traps: ["Canada", "Svezia", "Russia"],
        },
        {
          type: "storia",
          question: "Quale guerra è durata più a lungo?",
          answer: "Guerra dei Cent'anni",
          traps: ["Guerra dei Trent'anni", "Guerra fredda", "Reconquista"],
        },
        {
          type: "cultura",
          question: "Quale strumento ha più corde?",
          answer: "Pianoforte",
          traps: ["Arpa", "Chitarra", "Violino"],
        },
        {
          type: "natura",
          question: "Quale uccello può volare all'indietro?",
          answer: "Colibrì",
          traps: ["Aquila", "Falco", "Passero"],
        },
        {
          type: "scienza",
          question: "Qual è l'elemento più abbondante nell'universo?",
          answer: "Idrogeno",
          traps: ["Ossigeno", "Carbonio", "Elio"],
        },
        {
          type: "geografia",
          question: "Quale montagna cresce ogni anno?",
          answer: "Monte Everest",
          traps: ["Monte Bianco", "Kilimanjaro", "Monte Fuji"],
        },
        {
          type: "storia",
          question: "Chi ha inventato la stampa?",
          answer: "Bi Sheng",
          traps: ["Gutenberg", "Caxton", "Plantin"],
        },
        {
          type: "cultura",
          question: "Quale paese produce più caffè?",
          answer: "Brasile",
          traps: ["Colombia", "Vietnam", "Etiopia"],
        },
        {
          type: "natura",
          question: "Quale animale ha più stomaci?",
          answer: "Mucca",
          traps: ["Pecora", "Cavallo", "Maiale"],
        },
        {
          type: "scienza",
          question: "A che temperatura l'acqua è più densa?",
          answer: "4°C",
          traps: ["0°C", "20°C", "100°C"],
        },
        {
          type: "geografia",
          question: "Quale paese ha la più alta aspettativa di vita?",
          answer: "Monaco",
          traps: ["Giappone", "Svizzera", "Singapore"],
        },
        {
          type: "storia",
          question: "Quale rivoluzione è avvenuta per prima?",
          answer: "Rivoluzione inglese",
          traps: [
            "Rivoluzione francese",
            "Rivoluzione americana",
            "Rivoluzione russa",
          ],
        },
        {
          type: "cultura",
          question: "Quale sport è stato inventato per primo?",
          answer: "Lotta",
          traps: ["Corsa", "Nuoto", "Boxe"],
        },
        {
          type: "natura",
          question: "Quale animale vive più a lungo?",
          answer: "Medusa immortale",
          traps: ["Tartaruga", "Balena", "Squalo"],
        },
        {
          type: "scienza",
          question: "Quante dimensioni ha lo spazio-tempo secondo Einstein?",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "geografia",
          question: "Quale fiume attraversa più paesi?",
          answer: "Danubio",
          traps: ["Nilo", "Rio delle Amazzoni", "Reno"],
        },
        {
          type: "storia",
          question: "Che lingua parlava Gesù?",
          answer: "Aramaico",
          traps: ["Ebraico", "Latino", "Greco"],
        },
        {
          type: "cultura",
          question: "Quale paese ha inventato la pasta?",
          answer: "Cina",
          traps: ["Italia", "Grecia", "Persia"],
        },
      ],
      pt: [
        {
          type: "cultura",
          question: "Onde foi inventado o croissant?",
          answer: "Áustria",
          traps: ["França", "Itália", "Bélgica"],
        },
        {
          type: "natureza",
          question: "Qual é o animal mais rápido em terra?",
          answer: "Guepardo",
          traps: ["Águia-real", "Lebre", "Zebra"],
        },
        {
          type: "arte",
          question: "Quem pintou a Mona Lisa?",
          answer: "Leonardo da Vinci",
          traps: ["Michelangelo", "Rafael", "Botticelli"],
        },
        {
          type: "geografia",
          question: "Qual é a capital da Austrália?",
          answer: "Canberra",
          traps: ["Sydney", "Melbourne", "Brisbane"],
        },
        {
          type: "geografia",
          question: "Qual é o maior oceano do mundo?",
          answer: "Oceano Pacífico",
          traps: ["Oceano Atlântico", "Oceano Índico", "Oceano Ártico"],
        },
        {
          type: "história",
          question: "Quem inventou a lâmpada elétrica?",
          answer: "Thomas Edison",
          traps: ["Nikola Tesla", "Benjamin Franklin", "Alexander Bell"],
        },
        {
          type: "ciência",
          question: "Quantos corações tem um polvo?",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "cultura",
          question: "Em que país foi inventado o sushi?",
          answer: "China",
          traps: ["Japão", "Coreia", "Tailândia"],
        },
        {
          type: "natureza",
          question: "Que animal não consegue andar para trás?",
          answer: "Canguru",
          traps: ["Elefante", "Girafa", "Pinguim"],
        },
        {
          type: "ciência",
          question: "Que planeta é o mais quente do sistema solar?",
          answer: "Vênus",
          traps: ["Mercúrio", "Marte", "Júpiter"],
        },
        {
          type: "geografia",
          question: "Que país tem mais fusos horários?",
          answer: "França",
          traps: ["Rússia", "Estados Unidos", "China"],
        },
        {
          type: "história",
          question: "Que povo inventou o papel?",
          answer: "Chineses",
          traps: ["Egípcios", "Gregos", "Romanos"],
        },
        {
          type: "natureza",
          question: "Qual é o maior mamífero terrestre?",
          answer: "Elefante africano",
          traps: ["Baleia azul", "Rinoceronte", "Hipopótamo"],
        },
        {
          type: "cultura",
          question: "Que bebida contém mais cafeína?",
          answer: "Chá matcha",
          traps: ["Café expresso", "Red Bull", "Coca-Cola"],
        },
        {
          type: "ciência",
          question: "Que órgão humano consome mais energia?",
          answer: "Cérebro",
          traps: ["Coração", "Fígado", "Músculos"],
        },
        {
          type: "geografia",
          question: "Qual é o maior deserto do mundo?",
          answer: "Antártica",
          traps: ["Saara", "Gobi", "Kalahari"],
        },
        {
          type: "história",
          question: "Que civilização inventou a escrita?",
          answer: "Sumérios",
          traps: ["Egípcios", "Chineses", "Gregos"],
        },
        {
          type: "natureza",
          question: "Que fruta contém mais vitamina C?",
          answer: "Acerola",
          traps: ["Laranja", "Limão", "Kiwi"],
        },
        {
          type: "ciência",
          question: "Que metal é líquido à temperatura ambiente?",
          answer: "Mercúrio",
          traps: ["Chumbo", "Estanho", "Zinco"],
        },
        {
          type: "cultura",
          question: "Que país inventou a pizza?",
          answer: "Grécia antiga",
          traps: ["Itália", "Estados Unidos", "França"],
        },
        {
          type: "natureza",
          question: "Que animal tem a mordida mais forte?",
          answer: "Crocodilo do Nilo",
          traps: ["Grande tubarão branco", "Leão", "Hiena"],
        },
        {
          type: "geografia",
          question: "Que país tem a costa mais longa do mundo?",
          answer: "Canadá",
          traps: ["Noruega", "Austrália", "Rússia"],
        },
        {
          type: "ciência",
          question: "Quantos ossos tem um tubarão?",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "história",
          question: "Quem descobriu a América primeiro?",
          answer: "Leif Erikson",
          traps: ["Cristóvão Colombo", "Américo Vespúcio", "Magalhães"],
        },
        {
          type: "cultura",
          question: "Que país bebe mais chá per capita?",
          answer: "Turquia",
          traps: ["China", "Índia", "Inglaterra"],
        },
        {
          type: "natureza",
          question: "Que inseto pode levantar 50 vezes o seu peso?",
          answer: "Formiga",
          traps: ["Besouro", "Abelha", "Gafanhoto"],
        },
        {
          type: "ciência",
          question: "Que cor absorve mais calor?",
          answer: "Preto",
          traps: ["Vermelho", "Azul escuro", "Roxo"],
        },
        {
          type: "geografia",
          question: "Que cidade é apelidada de 'Veneza do Norte'?",
          answer: "Amesterdão",
          traps: ["Estocolmo", "Bruges", "São Petersburgo"],
        },
        {
          type: "história",
          question: "Que império durou mais tempo?",
          answer: "Império bizantino",
          traps: ["Império romano", "Império otomano", "Império britânico"],
        },
        {
          type: "cultura",
          question: "Que queijo é mais consumido no mundo?",
          answer: "Mozzarella",
          traps: ["Cheddar", "Gouda", "Camembert"],
        },
        {
          type: "natureza",
          question: "Que animal dorme mais por dia?",
          answer: "Coala",
          traps: ["Preguiça", "Gato", "Morcego"],
        },
        {
          type: "ciência",
          question: "Que gás compõe principalmente a atmosfera?",
          answer: "Nitrogênio",
          traps: ["Oxigênio", "Dióxido de carbono", "Argônio"],
        },
        {
          type: "geografia",
          question: "Que país tem mais lagos no mundo?",
          answer: "Finlândia",
          traps: ["Canadá", "Suécia", "Rússia"],
        },
        {
          type: "história",
          question: "Que guerra durou mais tempo?",
          answer: "Guerra dos Cem Anos",
          traps: ["Guerra dos Trinta Anos", "Guerra Fria", "Reconquista"],
        },
        {
          type: "cultura",
          question: "Que instrumento tem mais cordas?",
          answer: "Piano",
          traps: ["Harpa", "Guitarra", "Violino"],
        },
        {
          type: "natureza",
          question: "Que ave pode voar para trás?",
          answer: "Beija-flor",
          traps: ["Águia", "Falcão", "Pardal"],
        },
        {
          type: "ciência",
          question: "Qual é o elemento mais abundante no universo?",
          answer: "Hidrogênio",
          traps: ["Oxigênio", "Carbono", "Hélio"],
        },
        {
          type: "geografia",
          question: "Que montanha cresce todos os anos?",
          answer: "Monte Everest",
          traps: ["Mont Blanc", "Kilimanjaro", "Monte Fuji"],
        },
        {
          type: "história",
          question: "Quem inventou a imprensa?",
          answer: "Bi Sheng",
          traps: ["Gutenberg", "Caxton", "Plantin"],
        },
        {
          type: "cultura",
          question: "Que país produz mais café?",
          answer: "Brasil",
          traps: ["Colômbia", "Vietnã", "Etiópia"],
        },
        {
          type: "natureza",
          question: "Que animal tem mais estômagos?",
          answer: "Vaca",
          traps: ["Ovelha", "Cavalo", "Porco"],
        },
        {
          type: "ciência",
          question: "A que temperatura a água é mais densa?",
          answer: "4°C",
          traps: ["0°C", "20°C", "100°C"],
        },
        {
          type: "geografia",
          question: "Que país tem a maior expectativa de vida?",
          answer: "Mônaco",
          traps: ["Japão", "Suíça", "Singapura"],
        },
        {
          type: "história",
          question: "Que revolução aconteceu primeiro?",
          answer: "Revolução inglesa",
          traps: [
            "Revolução francesa",
            "Revolução americana",
            "Revolução russa",
          ],
        },
        {
          type: "cultura",
          question: "Que esporte foi inventado primeiro?",
          answer: "Luta",
          traps: ["Corrida", "Natação", "Boxe"],
        },
        {
          type: "natureza",
          question: "Que animal vive mais tempo?",
          answer: "Água-viva imortal",
          traps: ["Tartaruga", "Baleia", "Tubarão"],
        },
        {
          type: "ciência",
          question: "Quantas dimensões tem o espaço-tempo segundo Einstein?",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "geografia",
          question: "Que rio atravessa mais países?",
          answer: "Danúbio",
          traps: ["Nilo", "Amazonas", "Reno"],
        },
        {
          type: "história",
          question: "Que língua Jesus falava?",
          answer: "Aramaico",
          traps: ["Hebraico", "Latim", "Grego"],
        },
        {
          type: "cultura",
          question: "Que país inventou a massa?",
          answer: "China",
          traps: ["Itália", "Grécia", "Pérsia"],
        },
      ],
      ar: [
        {
          type: "ثقافة",
          question: "أين تم اختراع الكرواسون؟",
          answer: "النمسا",
          traps: ["فرنسا", "إيطاليا", "بلجيكا"],
        },
        {
          type: "طبيعة",
          question: "ما هو أسرع حيوان على الأرض؟",
          answer: "الفهد",
          traps: ["النسر الذهبي", "الأرنب", "الحمار الوحشي"],
        },
        {
          type: "فن",
          question: "من رسم الموناليزا؟",
          answer: "ليوناردو دافنشي",
          traps: ["مايكل أنجلو", "رافائيل", "بوتيتشيلي"],
        },
        {
          type: "جغرافيا",
          question: "ما هي عاصمة أستراليا؟",
          answer: "كانبرا",
          traps: ["سيدني", "ملبورن", "بريزبن"],
        },
        {
          type: "جغرافيا",
          question: "ما هو أكبر محيط في العالم؟",
          answer: "المحيط الهادئ",
          traps: ["المحيط الأطلسي", "المحيط الهندي", "المحيط المتجمد الشمالي"],
        },
        {
          type: "تاريخ",
          question: "من اخترع المصباح الكهربائي؟",
          answer: "توماس إديسون",
          traps: ["نيكولا تيسلا", "بنجامين فرانكلين", "ألكسندر بيل"],
        },
        {
          type: "علم",
          question: "كم عدد القلوب في الأخطبوط؟",
          answer: "3",
          traps: ["1", "2", "4"],
        },
        {
          type: "ثقافة",
          question: "في أي بلد تم اختراع السوشي؟",
          answer: "الصين",
          traps: ["اليابان", "كوريا", "تايلاند"],
        },
        {
          type: "طبيعة",
          question: "أي حيوان لا يستطيع المشي للخلف؟",
          answer: "الكنغر",
          traps: ["الفيل", "الزرافة", "البطريق"],
        },
        {
          type: "علم",
          question: "أي كوكب هو الأسخن في النظام الشمسي؟",
          answer: "الزهرة",
          traps: ["عطارد", "المريخ", "المشتري"],
        },
        {
          type: "جغرافيا",
          question: "أي دولة لديها أكثر المناطق الزمنية؟",
          answer: "فرنسا",
          traps: ["روسيا", "الولايات المتحدة", "الصين"],
        },
        {
          type: "تاريخ",
          question: "أي شعب اخترع الورق؟",
          answer: "الصينيون",
          traps: ["المصريون", "اليونانيون", "الرومان"],
        },
        {
          type: "طبيعة",
          question: "ما هو أكبر حيوان ثديي على الأرض؟",
          answer: "الفيل الأفريقي",
          traps: ["الحوت الأزرق", "وحيد القرن", "فرس النهر"],
        },
        {
          type: "ثقافة",
          question: "أي مشروب يحتوي على أكثر كافيين؟",
          answer: "شاي الماتشا",
          traps: ["قهوة إسبريسو", "ريد بول", "كوكا كولا"],
        },
        {
          type: "علم",
          question: "أي عضو بشري يستهلك أكثر طاقة؟",
          answer: "الدماغ",
          traps: ["القلب", "الكبد", "العضلات"],
        },
        {
          type: "جغرافيا",
          question: "ما هي أكبر صحراء في العالم؟",
          answer: "القارة القطبية الجنوبية",
          traps: ["الصحراء الكبرى", "جوبي", "كالاهاري"],
        },
        {
          type: "تاريخ",
          question: "أي حضارة اخترعت الكتابة؟",
          answer: "السومريون",
          traps: ["المصريون", "الصينيون", "اليونانيون"],
        },
        {
          type: "طبيعة",
          question: "أي فاكهة تحتوي على أكثر فيتامين سي؟",
          answer: "الأسيرولا",
          traps: ["البرتقال", "الليمون", "الكيوي"],
        },
        {
          type: "علم",
          question: "أي معدن سائل في درجة حرارة الغرفة؟",
          answer: "الزئبق",
          traps: ["الرصاص", "القصدير", "الزنك"],
        },
        {
          type: "ثقافة",
          question: "أي دولة اخترعت البيتزا؟",
          answer: "اليونان القديمة",
          traps: ["إيطاليا", "الولايات المتحدة", "فرنسا"],
        },
        {
          type: "طبيعة",
          question: "أي حيوان له أقوى عضة؟",
          answer: "تمساح النيل",
          traps: ["القرش الأبيض الكبير", "الأسد", "الضبع"],
        },
        {
          type: "جغرافيا",
          question: "أي دولة لديها أطول ساحل في العالم؟",
          answer: "كندا",
          traps: ["النرويج", "أستراليا", "روسيا"],
        },
        {
          type: "علم",
          question: "كم عدد العظام في القرش؟",
          answer: "0",
          traps: ["206", "150", "300"],
        },
        {
          type: "تاريخ",
          question: "من اكتشف أمريكا أولاً؟",
          answer: "ليف إريكسون",
          traps: ["كريستوفر كولومبوس", "أمريكو فيسبوتشي", "ماجلان"],
        },
        {
          type: "ثقافة",
          question: "أي دولة تشرب أكثر شاي للفرد؟",
          answer: "تركيا",
          traps: ["الصين", "الهند", "إنجلترا"],
        },
        {
          type: "طبيعة",
          question: "أي حشرة يمكنها رفع 50 ضعف وزنها؟",
          answer: "النملة",
          traps: ["الخنفساء", "النحلة", "الجندب"],
        },
        {
          type: "علم",
          question: "أي لون يمتص أكثر حرارة؟",
          answer: "الأسود",
          traps: ["الأحمر", "الأزرق الداكن", "البنفسجي"],
        },
        {
          type: "جغرافيا",
          question: "أي مدينة تُلقب بـ'البندقية الشمالية'؟",
          answer: "أمستردام",
          traps: ["ستوكهولم", "بروج", "سان بطرسبرغ"],
        },
        {
          type: "تاريخ",
          question: "أي إمبراطورية استمرت أطول فترة؟",
          answer: "الإمبراطورية البيزنطية",
          traps: [
            "الإمبراطورية الرومانية",
            "الإمبراطورية العثمانية",
            "الإمبراطورية البريطانية",
          ],
        },
        {
          type: "ثقافة",
          question: "أي جبن يُستهلك أكثر في العالم؟",
          answer: "الموزاريلا",
          traps: ["التشيدار", "الجودا", "الكامامبير"],
        },
        {
          type: "طبيعة",
          question: "أي حيوان ينام أكثر في اليوم؟",
          answer: "الكوالا",
          traps: ["الكسلان", "القط", "الخفاش"],
        },
        {
          type: "علم",
          question: "أي غاز يشكل الغلاف الجوي بشكل أساسي؟",
          answer: "النيتروجين",
          traps: ["الأكسجين", "ثاني أكسيد الكربون", "الأرجون"],
        },
        {
          type: "جغرافيا",
          question: "أي دولة لديها أكثر بحيرات في العالم؟",
          answer: "فنلندا",
          traps: ["كندا", "السويد", "روسيا"],
        },
        {
          type: "تاريخ",
          question: "أي حرب استمرت أطول فترة؟",
          answer: "حرب المائة عام",
          traps: ["حرب الثلاثين عاماً", "الحرب الباردة", "الاسترداد"],
        },
        {
          type: "ثقافة",
          question: "أي آلة موسيقية لديها أكثر أوتار؟",
          answer: "البيانو",
          traps: ["القيثارة", "الجيتار", "الكمان"],
        },
        {
          type: "طبيعة",
          question: "أي طائر يمكنه الطيران للخلف؟",
          answer: "الطائر الطنان",
          traps: ["النسر", "الصقر", "العصفور"],
        },
        {
          type: "علم",
          question: "ما هو أكثر عنصر وفرة في الكون؟",
          answer: "الهيدروجين",
          traps: ["الأكسجين", "الكربون", "الهيليوم"],
        },
        {
          type: "جغرافيا",
          question: "أي جبل ينمو كل عام؟",
          answer: "جبل إيفرست",
          traps: ["مون بلان", "كليمنجارو", "جبل فوجي"],
        },
        {
          type: "تاريخ",
          question: "من اخترع المطبعة؟",
          answer: "بي شينغ",
          traps: ["جوتنبرغ", "كاكستون", "بلانتين"],
        },
        {
          type: "ثقافة",
          question: "أي دولة تنتج أكثر قهوة؟",
          answer: "البرازيل",
          traps: ["كولومبيا", "فيتنام", "إثيوبيا"],
        },
        {
          type: "طبيعة",
          question: "أي حيوان لديه أكثر معدات؟",
          answer: "البقرة",
          traps: ["الخروف", "الحصان", "الخنزير"],
        },
        {
          type: "علم",
          question: "في أي درجة حرارة يكون الماء أكثر كثافة؟",
          answer: "4 درجات مئوية",
          traps: ["0 درجة مئوية", "20 درجة مئوية", "100 درجة مئوية"],
        },
        {
          type: "جغرافيا",
          question: "أي دولة لديها أعلى متوسط عمر متوقع؟",
          answer: "موناكو",
          traps: ["اليابان", "سويسرا", "سنغافورة"],
        },
        {
          type: "تاريخ",
          question: "أي ثورة حدثت أولاً؟",
          answer: "الثورة الإنجليزية",
          traps: ["الثورة الفرنسية", "الثورة الأمريكية", "الثورة الروسية"],
        },
        {
          type: "ثقافة",
          question: "أي رياضة تم اختراعها أولاً؟",
          answer: "المصارعة",
          traps: ["الجري", "السباحة", "الملاكمة"],
        },
        {
          type: "طبيعة",
          question: "أي حيوان يعيش أطول فترة؟",
          answer: "قنديل البحر الخالد",
          traps: ["السلحفاة", "الحوت", "القرش"],
        },
        {
          type: "علم",
          question: "كم عدد أبعاد المكان-الزمن حسب أينشتاين؟",
          answer: "4",
          traps: ["3", "5", "11"],
        },
        {
          type: "جغرافيا",
          question: "أي نهر يعبر أكثر دول؟",
          answer: "الدانوب",
          traps: ["النيل", "الأمازون", "الراين"],
        },
        {
          type: "تاريخ",
          question: "أي لغة كان يتكلم بها المسيح؟",
          answer: "الآرامية",
          traps: ["العبرية", "اللاتينية", "اليونانية"],
        },
        {
          type: "ثقافة",
          question: "أي دولة اخترعت المعكرونة؟",
          answer: "الصين",
          traps: ["إيطاليا", "اليونان", "فارس"],
        },
      ],
    },
  },
};
