import { Question } from '@/types/gameTypes';

// 250 défis Double Dare répartis sur 3 niveaux (Hot, Extreme, Chaos) et 2 modes (Versus, Fusion)
export const doubleDareQuestions: Omit<Question, 'id' | 'roundNumber'>[] = [
  // ===== HOT 🔥 - VERSUS MODE (30 cartes) =====
  { text: "Décris ton/ta partenaire comme si tu étais dans un film interdit… sans rire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Ton/ta partenaire choisit une partie de ton corps à complimenter… sans la nommer.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Tu dois chuchoter quelque chose de gênant à ton/ta partenaire pendant 10 secondes.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Pendant 20 secondes, tu dois exécuter ce que ton/ta partenaire t'ordonne.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Imite ton/ta partenaire pendant un moment intime. Essaie de ne pas rire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Raconte le moment où tu as le plus fantasmé sur ton/ta partenaire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Dis un compliment coquin à ton/ta partenaire en le/la regardant dans les yeux pendant 10 secondes.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Ton/ta partenaire choisit un mot 'interdit' que tu dois glisser dans une phrase sensuelle.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Décris ce que tu porterais pour séduire ton/ta partenaire ce soir.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Fais semblant d'être dans une pub de parfum sexy avec ton/ta partenaire comme acteur principal.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Dis trois choses que tu aimerais que ton/ta partenaire te fasse… mais sans utiliser les mots 'toucher' ou 'embrasser'.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Envoie un regard 'interdit' à ton/ta partenaire pendant 15 secondes sans cligner des yeux.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Raconte un rêve érotique que tu as fait avec ton/ta partenaire (vrai ou inventé).", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Ton/ta partenaire te pose une question gênante. Tu dois répondre avec 100% d'honnêteté.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Danse de manière sensuelle pendant 20 secondes devant ton/ta partenaire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Décris le fantasme que tu n'as jamais osé partager.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Ton/ta partenaire choisit une zone de ton corps. Tu dois dire ce que tu aimerais qu'il/elle y fasse.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Rappelle le moment le plus sexy que vous avez vécu ensemble.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Fais un compliment coquin sur la tenue de ton/ta partenaire (même s'il/elle porte un pyjama).", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Murmure une proposition indécente à l'oreille de ton/ta partenaire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Dis ce qui t'excite le plus chez ton/ta partenaire physiquement.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Invente un surnom sexy pour ton/ta partenaire et explique pourquoi.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Fais une déclaration d'amour… mais version très coquine.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Choisis une chanson qui représente votre vie intime et explique pourquoi.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Décris en détail ce que tu ferais si vous étiez seuls sur une île déserte.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un mot. Tu dois construire une phrase sexy avec.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Rappelle un moment où tu as été jaloux(se) de quelqu'un qui regardait ton/ta partenaire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Dis quelque chose de coquin que tu n'as jamais osé dire.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Explique pourquoi ton/ta partenaire est irrésistible en 3 mots sensuels.", theme: 'hot-versus', level: 'hot', mode: 'versus' },
  { text: "Donne un aperçu de ce que tu aimerais faire après cette partie.", theme: 'hot-versus', level: 'hot', mode: 'versus' },

  // ===== HOT 🔥 - FUSION MODE (30 cartes) =====
  { text: "Regardez-vous dans les yeux pendant 30 secondes sans parler ni rire.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Chuchotez-vous simultanément un secret coquin à l'oreille.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez ensemble une phrase sensuelle en alternant un mot chacun.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Inventez ensemble un surnom de couple coquin et expliquez-le.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Mimez ensemble une scène de film romantique… version très hot.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Racontez à deux voix votre premier moment intime ensemble.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez une chorégraphie sexy de 15 secondes ensemble.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Dites-vous 3 compliments coquins en même temps.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Inventez ensemble le titre d'un film classé X inspiré de votre couple.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Choisissez ensemble un endroit insolite où vous aimeriez faire l'amour.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez ensemble une liste de 5 fantasmes à réaliser.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Racontez ensemble ce que vous feriez si vous étiez invisibles pendant 1 heure.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Imaginez ensemble votre soirée parfaite… sans censure.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Synchronisez vos respirations pendant 20 secondes en vous regardant.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Choisissez ensemble une chanson sexy pour votre couple et dansez dessus.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez ensemble un code secret pour parler de sexe en public.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Racontez à deux le moment le plus gênant que vous avez vécu ensemble.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Inventez ensemble un cocktail aphrodisiaque et donnez-lui un nom coquin.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Décrivez ensemble ce que vous porteriez pour une soirée très privée.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez ensemble une playlist de 5 chansons pour vos moments intimes.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Mimez ensemble une scène interdite aux moins de 18 ans… sans toucher.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Racontez ensemble un fantasme que vous partagez.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Inventez ensemble un jeu coquin rien que pour vous deux.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Choisissez ensemble 3 mots interdits pour le reste de la partie. Celui qui en dit un perd.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Décrivez ensemble votre week-end idéal… version non-censurée.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez ensemble un top 3 de vos moments les plus chauds.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Imaginez ensemble ce que vous feriez si vous aviez la maison pour vous pendant 24h.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Racontez ensemble le souvenir le plus embarrassant de votre vie de couple.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Synchronisez un geste sensuel et faites-le en même temps.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },
  { text: "Créez ensemble le menu d'un dîner aphrodisiaque parfait.", theme: 'hot-fusion', level: 'hot', mode: 'fusion' },

  // ===== EXTREME 😈 - VERSUS MODE (40 cartes) =====
  { text: "Chacun doit avouer une chose qu'il/elle a envie de faire… mais n'a jamais osé dire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Échangez vos téléphones pendant 2 minutes — un seul regard autorisé.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Dis un fantasme secret impliquant ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un défi physique à réaliser. Tu ne peux pas refuser.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte en détail le moment où tu as le plus désiré ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Fais exactement ce que ton/ta partenaire te demande pendant 30 secondes.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Décris ce que tu ferais à ton/ta partenaire si vous étiez seuls maintenant.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Montre à ton/ta partenaire le message le plus osé que tu lui as envoyé.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue quelque chose que tu as toujours voulu essayer au lit.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire choisit une position. Tu dois la décrire en détail.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte ton rêve érotique le plus intense.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire te pose 3 questions embarrassantes. Tu dois répondre à toutes.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Décris en détail ce qui te fait le plus craquer chez ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue un endroit insolite où tu aimerais faire l'amour.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un scénario. Tu dois l'enrichir de détails coquins.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte la dernière fois où tu as vraiment eu envie de ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Fais une promesse coquine à ton/ta partenaire pour ce soir.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue ce que tu penses quand tu regardes ton/ta partenaire de manière intense.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire mime quelque chose. Tu dois deviner et le faire mieux.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Décris un fantasme que tu aimerais réaliser dans les 30 prochains jours.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue quelque chose que tu as fait en pensant à ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte le moment le plus audacieux de votre relation.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire choisit un vêtement que tu portes. Décris comment tu l'enlèverais de manière sexy.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Dis 5 choses que tu aimerais que ton/ta partenaire te fasse ce soir.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue un moment où tu as secrètement fantasmé sur ton/ta partenaire en public.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte en détail ce que tu ferais si ton/ta partenaire te donnait carte blanche.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire te montre une photo de lui/elle. Dis ce que ça te fait.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue quelque chose de très intime que tu n'as jamais dit.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Décris ton scénario parfait pour une nuit inoubliable.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un défi osé. Tu as 10 secondes pour l'accepter ou subir un gage.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte la première fois où tu as vraiment désiré ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue ce que tu aimerais que ton/ta partenaire porte (ou ne porte pas) ce soir.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Décris en détail ce que tu ferais pour séduire ton/ta partenaire maintenant.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire choisit une partie de son corps. Dis ce que tu aimerais y faire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Raconte ton fantasme le plus secret en regardant ton/ta partenaire dans les yeux.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue quelque chose que tu aimerais essayer mais que tu n'as jamais osé proposer.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Fais une démonstration (habillé) de ce que tu aimerais faire à ton/ta partenaire.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Ton/ta partenaire te défie. Relève-le ou accepte le gage qu'il/elle impose.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Décris le moment le plus intense de votre vie intime.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },
  { text: "Avoue ce qui te passe par la tête quand ton/ta partenaire te regarde intensément.", theme: 'extreme-versus', level: 'extreme', mode: 'versus' },

  // ===== EXTREME 😈 - FUSION MODE (40 cartes) =====
  { text: "Vous avez 30 secondes pour improviser une scène 'spicy' sans toucher.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Faites un défi ensemble les yeux bandés (l'un guide l'autre).", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble votre fantasme commun le plus osé.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble un scénario interdit de A à Z.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Mimez ensemble une scène très hot… en silence et sans toucher.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Choisissez ensemble 3 choses à essayer dans les 7 prochains jours.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez à deux le moment le plus audacieux de votre relation.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble la description d'une nuit parfaite… sans censure.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Inventez ensemble un challenge coquin pour ce soir.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Décrivez ensemble en détail ce que vous feriez si personne ne pouvait vous voir pendant 1 heure.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble une bucket list de 10 choses à faire au lit.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble votre souvenir le plus embarrassant… et le plus excitant.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Mimez ensemble quelque chose d'interdit sans dire un mot.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Imaginez ensemble un week-end sans limites et décrivez-le.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble le script d'un film classé X avec vous deux en acteurs.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Choisissez ensemble un endroit public où vous aimeriez faire quelque chose d'osé.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble ce qui vous excite le plus chez l'autre.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble une chorégraphie sensuelle et exécutez-la.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Inventez ensemble un jeu interdit rien que pour vous.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Décrivez ensemble en détail votre soirée idéale après cette partie.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Choisissez ensemble 5 positions à essayer et classez-les par ordre de préférence.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble un fantasme que vous n'avez jamais réalisé.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble un pacte secret pour les 30 prochains jours.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Mimez ensemble votre première fois… version améliorée.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Inventez ensemble un code pour vous dire des choses coquines en public.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Décrivez ensemble ce que vous feriez dans un jacuzzi privé.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble un menu aphrodisiaque et décrivez comment vous le serviriez.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble le moment où vous vous êtes le plus désirés.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Choisissez ensemble une playlist de 10 chansons pour vos moments intimes.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Inventez ensemble un défi physique osé et réalisez-le.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Décrivez ensemble votre fantasme de vacances… sans aucune limite.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble le règlement d'un jeu coquin personnalisé.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble ce que vous feriez si vous aviez une chambre d'hôtel de luxe pour 24h.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Mimez ensemble une scène que vous aimeriez vivre ce soir.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Inventez ensemble 5 surnoms très coquins l'un pour l'autre.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble un challenge de 7 jours et engagez-vous à le réaliser.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Décrivez ensemble en détail ce que vous feriez dans un endroit interdit.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Racontez ensemble votre meilleur souvenir intime et comment l'améliorer.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Créez ensemble une liste de 10 fantasmes communs à cocher.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },
  { text: "Synchronisez un regard intense pendant 45 secondes et imaginez la suite ensemble.", theme: 'extreme-fusion', level: 'extreme', mode: 'fusion' },

  // ===== CHAOS 💀 - VERSUS MODE (40 cartes) =====
  { text: "Tu as 10 secondes : avoue ton fantasme le plus extrême ou accepte n'importe quel gage imposé par ton/ta partenaire.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire prend ton téléphone et lit à voix haute le dernier message osé que tu as envoyé.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris en détail quelque chose d'extrême que tu aimerais essayer.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te donne 3 défis. Tu dois en choisir un et le réaliser maintenant.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue quelque chose que personne ne sait… même pas ton/ta partenaire.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Fais exactement ce que ton/ta partenaire te demande pendant 1 minute, sans exception.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Raconte en détail ton rêve érotique le plus fou.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire choisit une vérité extrême. Tu dois y répondre sans filtre.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris ce que tu ferais si tu avais le contrôle total sur ton/ta partenaire pendant 1 heure.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Montre le contenu le plus osé de ton téléphone.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue la pensée la plus interdite que tu as eue récemment.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un scénario extrême. Tu dois le compléter sans censure.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris ton fantasme ultime comme si tu écrivais un roman érotique.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Fais une démonstration (habillé) de ce que tu aimerais vraiment faire maintenant.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue quelque chose que tu as toujours voulu essayer mais jamais osé demander.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te pose une question ultra-gênante. Réponds avec 100% de vérité.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris en détail ce que tu ferais si vous étiez dans un lieu totalement privé maintenant.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Raconte le moment le plus intense et extrême que tu as vécu.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un défi limite. Accepte ou subis 3 gages de son choix.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue ce que tu penses vraiment quand ton/ta partenaire fait quelque chose de sexy.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris ton scénario le plus osé impliquant un lieu public.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Fais une promesse extrême à ton/ta partenaire pour cette nuit.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire mime quelque chose de très osé. Devine et fais mieux.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue un désir secret que tu n'as jamais partagé avec personne.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Raconte la dernière fois où tu as vraiment perdu le contrôle avec ton/ta partenaire.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire choisit une partie de ton corps. Dis exactement ce que tu aimerais qu'il/elle y fasse.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris en détail ce que tu ferais si ton/ta partenaire te donnait un passe-droit total.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue quelque chose d'extrême que tu as déjà fait ou que tu aimerais faire.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te fixe pendant 30 secondes. Dis exactement ce que ça te fait.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Raconte ton fantasme le plus tabou en détail.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Fais 3 promesses osées à ton/ta partenaire pour les prochaines 24 heures.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te donne un mot. Construis un scénario extrême autour de ce mot.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue ce que tu aimerais que ton/ta partenaire te fasse… sans aucune limite.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris le scénario le plus fou que tu pourrais imaginer pour vous deux.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire choisit un fantasme. Tu dois l'enrichir de détails explicites.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Raconte quelque chose que tu as fait en secret et qui impliquait ton/ta partenaire.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Fais une liste de 10 choses extrêmes que tu aimerais essayer.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Ton/ta partenaire te défie de faire quelque chose d'osé. Fais-le ou accepte 5 gages.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Avoue ton désir le plus secret concernant ton/ta partenaire.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },
  { text: "Décris en détail ce que tu ferais si vous aviez une nuit sans aucune règle.", theme: 'chaos-versus', level: 'chaos', mode: 'versus' },

  // ===== CHAOS 💀 - FUSION MODE (40 cartes) =====
  { text: "Créez ensemble le scénario le plus fou et osé possible. Vous avez 2 minutes.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble votre fantasme commun le plus extrême sans aucune censure.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Mimez ensemble une scène ultra-hot… les yeux bandés et en silence.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble une bucket list de 20 choses osées à faire ensemble.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Inventez ensemble un challenge extrême pour les 7 prochains jours et engagez-vous.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble le moment le plus intense de votre vie… et comment le surpasser.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble le script complet d'une nuit sans limites.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Choisissez ensemble 10 choses interdites à essayer dans les 30 prochains jours.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Décrivez ensemble en détail ce que vous feriez si personne ne pouvait jamais le savoir.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble un jeu personnalisé ultra-osé avec 10 règles.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble votre fantasme le plus tabou.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Inventez ensemble un week-end sans aucune limite et planifiez-le.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Mimez ensemble quelque chose d'extrême que vous n'avez jamais fait.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble une liste de 15 positions et classez-les par audace.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Décrivez ensemble ce que vous feriez dans une villa privée pendant 48h.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Choisissez ensemble 5 lieux publics où vous oseriez faire quelque chose d'interdit.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble votre souvenir le plus audacieux… et comment le dépasser.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble un pacte secret ultra-osé pour les prochains mois.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Inventez ensemble un challenge de 30 jours avec une récompense finale.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Décrivez ensemble en détail votre nuit parfaite… version non-censurée.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble le menu d'une soirée aphrodisiaque extrême.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble ce qui vous excite le plus… sans aucune retenue.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Mimez ensemble votre fantasme commun le plus osé.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Inventez ensemble un rituel secret ultra-sensuel rien que pour vous.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble un top 20 de vos moments les plus chauds et notez-les.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Décrivez ensemble ce que vous feriez si vous aviez carte blanche totale.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Choisissez ensemble 10 fantasmes communs et planifiez comment les réaliser.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble le moment où vous vous êtes le plus lâchés.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble une playlist de 20 chansons pour vos nuits les plus hot.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Inventez ensemble un code ultra-secret pour parler de choses interdites en public.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Décrivez ensemble votre vacances de rêve… version totalement décomplexée.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble un contrat de 10 règles osées pour votre couple.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble ce que vous feriez dans une suite d'hôtel de luxe pour 72h.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Mimez ensemble une scène que vous aimeriez vivre… sans aucune limite.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Inventez ensemble 10 surnoms ultra-coquins et leur signification.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble un challenge de 90 jours avec paliers et récompenses.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Décrivez ensemble en détail votre fantasme ultime commun.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Racontez ensemble votre meilleur moment intime et imaginez comment le multiplier par 10.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Créez ensemble une liste de 25 défis osés à cocher avant la fin de l'année.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
  { text: "Synchronisez un regard ultra-intense pendant 60 secondes et décrivez ensemble ce que vous ressentez.", theme: 'chaos-fusion', level: 'chaos', mode: 'fusion' },
];

export const transformDoubleDareQuestion = (question: any, index: number): Question => ({
  id: (index + 1).toString(),
  text: question.text,
  theme: question.theme,
  roundNumber: index + 1,
  level: question.level,
  mode: question.mode,
});

export function useDoubleDareQuestions() {
  const getRandomQuestion = (level?: 'hot' | 'extreme' | 'chaos', mode?: 'versus' | 'fusion') => {
    let filteredQuestions = doubleDareQuestions;

    // Filter by level if specified
    if (level) {
      filteredQuestions = filteredQuestions.filter(q => q.level === level);
    }

    // Filter by mode if specified
    if (mode) {
      filteredQuestions = filteredQuestions.filter(q => q.mode === mode);
    }

    const randomIndex = Math.floor(Math.random() * filteredQuestions.length);
    return transformDoubleDareQuestion(filteredQuestions[randomIndex], randomIndex);
  };

  const getQuestionsByLevel = (level: 'hot' | 'extreme' | 'chaos') => {
    return doubleDareQuestions
      .filter(q => q.level === level)
      .map((q, index) => transformDoubleDareQuestion(q, index));
  };

  const getQuestionsByMode = (mode: 'versus' | 'fusion') => {
    return doubleDareQuestions
      .filter(q => q.mode === mode)
      .map((q, index) => transformDoubleDareQuestion(q, index));
  };

  return {
    getRandomQuestion,
    getQuestionsByLevel,
    getQuestionsByMode,
    totalQuestions: doubleDareQuestions.length,
  };
}
